
---
title: "Sam Clifford - Full publication list"
date: "`r format(Sys.Date(), '%d %b %Y')`"
output: 
  tufterhandout::html_tufte_handout:
    self_contained: false
    keep_md: true
    css: ["resume.css", "tufterhandout.css"]
    toc: true
    toc_depth: 2
    includes:
      in_header: header.html
bibliography: resume.bib
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


<aside>
* <a href="https://github.com/samclifford">GitHub</a>
    * [`mmcc`](http://mmcc.njtierney.com/)
    * [`mgcv.helper`](https://github.com/samclifford/mgcv.helper)
* <a href="http://samclifford.info">Blog</a>
* <a href="https://eprints.qut.edu.au/view/person/Clifford,_Sam.html">QUT ePrints</a>
* <a href="https://scholar.google.com.au/citations?hl=en&user=KbrnxeoAAAAJ&view_op=list_works">Google Scholar</a>
* <a href="http://orcid.org/0000-0002-3774-3882">ORCID</a>

</aside>

For a more detailed biography and list of current projects, go [home](index.html).

# ACEMS

## Dengue 

I am working with colleagues at QUT and <a href="http://www.qimrberghofer.edu.au/diseases/mosquito-borne-viruses/">QIMR</a> to investigate the replication and spread of Dengue fever.

<aside>
2017-: <a href="http://www.qimrberghofer.edu.au/diseases/mosquito-borne-viruses/">Dengue fever (QIMR)</a>
</aside>

## Great Barrier Reef

<aside>
2016: <a href="https://www.virtualreef.org.au/">Monitoring Through Many Eyes</a>
</aside>


---------------------------------------------------------
Citation                 Description
------------------------ --------------------------------
@reefaesthetics          Gathering information from experts and citizen scientists in a virtual environment to understand what people believe makes an aesthetically pleasing reef

--------------------------------------------------------

## Jaguars

<aside>
2016: <a href="http://vis.stats.technology/">Many Eyes on the Wild</a>
</aside>

---------------------------------------------------------
Citation                 Description
------------------------ --------------------------------
@jaguarspatial           Spatial modelling of presence only data with a variety of statistical and machine learning techniques

@bednarz2016virtual      Using virtual environments to elicit information about ecosystems

--------------------------------------------------------


# Air Quality and Health

<aside>
2010-2015: <a href="https://www.qut.edu.au/research/our-research/institutes-centres-and-research-groups/international-laboratory-for-air-quality-and-health">International Laboratory for Air Quality and Health</a>
</aside>

---------------------------------------------------------
Citation                 Description
------------------------ --------------------------------
@uptechmain              Main UPTECH paper detailing the inflammatory and pulmonary response to ultrafine particles

@rusdinpaper1            The relationship between indoor and outdoor air quality in primary schools

@MORAWSKA201775          Indoor sources of exposure in the home, office, school and aged care facilities

@rahman2017nox           Land use regression modelling with variable selection of NO$_\mathrm{x}$ and NO$_2$ concentrations

@rahman2017estimate      Bayesian GAMs used to model urban background particle concentrations and the contribution of new particle formation

@salimi2017nocturnal     Investigating new particle formation events that occur outside normal conditions

@rivas2017identification Identification of problems with DustTrak performance seen during measurement campaigns

@yeganeh2017satellite    A variety of models used to estimate air pollution concentrations from satellite imagery

@salonen2016endotoxin    A review of endotoxin concentrations in a range of indoor environments around the world

@mcgarry2016application  Characterisation of air quality in the workplace with multiple instruments

@salthammer2016children  Impact of climate and air pollution on children's health at school

@ehsan                   Generalised Linear Mixed Models for understanding the effects of different surface treatments in a nanomaterial milling process

@fungireview             A review paper on fungi concentrations in schools around the world

@salonen2014             Concentrations of fungi in primary school classrooms

@rohanpm10               Predictive model for whether or not midday new particle formation events will occur based on morning PM$_{10}$ and visibility

@tenzin1                 Children's exposure to air pollution in rural Bhutan

@ezz2015                 Methods paper for the UPTECH project

@PBDEs                   Multinomial regression modelling to look at the relative proportions of various polybrominated diphenyl ethers across classrooms

@thermodenuder            Semi-parametric regression used to model particle losses in aerosol measuring equipment

@farhadcluster           Application of clustering techniques to particle size distribution data to understand common source signatures

@emacpaper               Mathematical and statistical models for particle deposition inside the lung

@mandanantpaper          Analysis of inhaled particles in primary school children

@rusdinAER               Bayesian hierarchical models for calculating air exchange rates and particle deposition rates associated with classroom activities

@endotoxin               Concentrations of endotoxins in primary school classrooms

@molgaard2013             Work that came out of a visit to Helsinki, Finland, using Bayesian GAMs with autocorrelated errors to understand air quality in multiple European cities

@farhadpaper              Spatial variation of air quality within primary schools

@paper2                   Spatio-temporal model in INLA of air pollution in Brisbane, Australia

@bayesiansplineschapter   A book chapter on various implementations of Bayesian spline regression

@finlandpaper             A preprint of an unpublished paper looking into Bayesian GAMs with autocorrelated errors

@Clifford2011             Using GAMs to model temporal trends and covariate effects for PNC in Helsinki, Finland

---------------------------------------------------------

# Other items


---------------------------------------------------------
Citation                 Description
------------------------ --------------------------------
@zoe2017ofmdpm           Overfitted mixtures and Dirichlet process mixtures for spike classification

@herdsa2016              Redesign of a first year unit with blended learning to improve student engagement and success

@falk                    Review paper on modern statistical methods for analysing spatial data

---------------------------------------------------------


# Conference items


---------------------------------------------------------
Citation                 Description
------------------------ --------------------------------
@falcao2016influence     Modern statistical techniques for understanding indoor/outdoor relationships in air pollution
 
@eacclifford             A missing data model for estimating cigarette exposure from survey data and partially complete blood tests

@eacmazaheri             Comparing two methods of exposure assessment 

@eacrahman               Source characterisation in an urban area

@jayanAAC                Land Use Regression for air pollution

@uptechIA2014            Synthesis of indoor air pollution results from UPTECH study

@emactalk                Presentation of the work in @emacpaper

@ntsydney                Comparison of inhaled particle doses for Italian and Australian students

@clustering              Identification of subpopulations in epidemiological studies

@isbaposter              Poster on spatio-temporal modelling of air quality at ISBA2012

@bnpposter               Poster on spatio-temporal modelling of air quality at 8BNP

---------------------------------------------------------


# Theses

---------------------------------------------------------
Citation                 Description
------------------------ --------------------------------
@phdthesis               _Spatio-temporal modelling of ultrafine particle number concentration_ - Using the Generalised Additive Model to model temporal trends in ultrafine particle number concentration with penalised splines and spatial trends with Gaussian Markov Random fields.

@honours                 Honours thesis on dispersion of a compount in shear-augmented flow 

---------------------------------------------------------



# References