---
title: List of Publications
bibliography: "resume.bib"
output:
  md_document
link-citations: yes
author: Sam Clifford
date: '2018-02-14'
csl: chicago-author-date.csl
disableComments: true
---

This page contains selected references from major projects including doctoral and postdoctoral work. For the most up to date publication list, please check [Google Scholar](https://scholar.google.com.au/citations?user=KbrnxeoAAAAJ) and [ORCID](http://orcid.org/0000-0002-3774-3882).


## Theses

---------------------------------------------------------
Citation                 Description
------------------------ --------------------------------
@phdthesis               _Spatio-temporal modelling of ultrafine particle number concentration_ - Using the Generalised Additive Model to model temporal trends in ultrafine particle number concentration with penalised splines and spatial trends with Gaussian Markov Random fields.

@honours                 Honours thesis on dispersion of a compount in shear-augmented flow
---------------------------------------------------------


## Citizen science for spatial statistics

---------------------------------------------------------
Citation                 Description
------------------------ --------------------------------
@reefmain                Spatio-temporal model of coral cover derived from traditional monitoring and citizen science elicitation of captured images

@reefaesthetics          Gathering information from experts and citizen scientists in a virtual environment to understand what people believe makes an aesthetically pleasing reef

@jaguarspatial           Spatial modelling of presence only data with a variety of statistical and machine learning techniques

@bednarz2016virtual      Using virtual environments to elicit information about ecosystems

--------------------------------------------------------



## Urban air pollution and its health effects

---------------------------------------------------------
Citation                 Description
------------------------ --------------------------------
@uptechmain              Main UPTECH paper detailing the inflammatory and pulmonary response to ultrafine particles

@MORAWSKA201775          Indoor sources of exposure in the home, office, school and aged care facilities

@rahman2017nox           Land use regression modelling with variable selection of NO$_\mathrm{x}$ and NO$_2$ concentrations

@rahman2017estimate      Bayesian GAMs used to model urban background particle concentrations and the contribution of new particle formation

@yeganeh2017satellite    Application of statistical and machine learning models used to estimate air pollution concentrations from satellite imagery

@salthammer2016children  Impact of climate and air pollution on children's health at school

@PBDEs                   Multinomial regression modelling to look at the relative proportions of various polybrominated diphenyl ethers across classrooms

@emacpaper               Mathematical and statistical models for particle deposition inside the lung

@mandanantpaper          Analysis of inhaled particles in primary school children

@paper2                  Spatio-temporal model in INLA of air pollution in Brisbane, Australia
---------------------------------------------------------


## Non-parametric modelling of time series data

---------------------------------------------------------
Citation                 Description
------------------------ --------------------------------
@zoe2017ofmdpm           Overfitted mixtures and Dirichlet process mixtures for spike classification

@bayesiansplineschapter  A book chapter on various implementations of Bayesian spline regression

@finlandpaper            A preprint of an unpublished paper looking into Bayesian GAMs with autocorrelated errors

@Clifford2011            Using GAMs to model temporal trends and covariate effects for PNC in Helsinki, Finland

---------------------------------------------------------

## Atmospheric processes and instrumentation

---------------------------------------------------------
Citation                 Description
------------------------ --------------------------------
@salimi2017nocturnal     New particle formation typically occurs during daylight; here we investigate evidence of night time events

@rivas2017identification Identification of problems with DustTrak performance seen during measurement campaigns -- indicating conditions under which this instrument shouldn't be used

@rohanpm10               Predictive model for whether or not midday new particle formation events will occur based on morning PM$_{10}$ and visibility

@thermodenuder           Semi-parametric regression used to model particle losses in aerosol measuring equipment
---------------------------------------------------------

## Teaching

---------------------------------------------------------
Citation                 Description
------------------------ --------------------------------
@herdsa2016              Redesign of a first year unit with blended learning to improve student engagement and success
---------------------------------------------------------

# References