---
title: Koalas
author: Sam Clifford
date: '2018-04-14'
slug: koalas
categories: ["research"]
bibliography: ../resume.bib
csl: ../chicago-author-date.csl
link-citations: yes
hasMath: true
---

For the last few months we've had a few [Vacation Research Experience Scheme students at ACEMS](https://acems.org.au/news/vres-koala-conservation) working on a project using drones and virtual reality technologies to monitor koalas. I'd not had much to do with the students over the time they'd been here other than occasionally sitting at the same table during lunch or a tea break. Now that they're up to the modelling stage of their work, I've been asked to help out with some advice and the occasional bit of coding.

A lot of what they're working on is related to the jaguar paper [@jaguarspatial] that I spent a lot of time on in 2016. Rather than presence only data from interviews, they've got traditional survey data, drone-based surveying, and expert elicitation with virtual environments which was a large part of the jaguar and reef projects [@bednarz2016virtual; @reefaesthetics]. We're looking at ways of making spatial predictions by fusing all this data together with binomial GLMs and beta regression. This has meant that three applied maths undergrads are learning a lot of statistics very quickly, as well as how to use [RStudio](https://www.rstudio.com/) and [GitKraken](https://www.gitkraken.com/) to share the data wrangling, analysis and visualisation code with each other such that they can all work on it. They've done an admirable job of picking up these technologies as well as ArcGIS, LaTeX and one of them's showing an interest in using Sweave/R Markdown to automate report writing.

I've certainly noticed that my coding practice has changed since 2016 and I'm working more and more with tidyverse approaches to analysis, returning results for things as data frames rather than vectors, writing my modelling code in such a way that it's ready for visualisation with [ggplot2](http://ggplot2.tidyverse.org/)`r tufte::margin_note("If you're not using ggplot2 by now what are you even doing?")`. I'm glad I put the work in to write a few functions up and put them in mgcv.helper [@mgcv.helper] as they're making their way into this work and some other work I'm revising for air pollution exposure for office workers. So I'm brushing up on meta-analysis techniques and ensuring I'm writing code that simplifies things for me and is easier to follow for the students.

The work is a really solid effort on the part of the students, and even with my short involvement I've seen them develop their skills very rapidly. They've received a fantastic experience from Erin Peterson (who I've worked with on reef and jaguar papers), Felipe Gonzalez (who I've worked with on air quality), Miles McBain and Jacinta Holloway (colleagues at ACEMS) to plan and execute the study and modelling.

## References