---
title: Bujo and the Blog
author: Sam Clifford
date: '2018-03-18'
slug: bujo-blog
categories: ["meta"]
bibliography: ../resume.bib
csl: ../chicago-author-date.csl
link-citations: yes
hasMath: true
---

## A brief history of time management attempts

Is [bullet journalling](http://www.bulletjournal.com) the best way to organise myself? Some friends of mine have posted about their use of bullet journalling on Twitter, either posting their daily list to keep themselves accountable or keeping track of work hours and garden schedules. I tried using the [Hipster PDA](http://www.43folders.com/2004/09/03/introducing-the-hipster-pda) many, many years ago to organise things, switched to using computer software like [iGTD](https://igtd.en.softonic.com/mac), phone apps, and found some success with just leaving a notepad instance open on my computer with a list of tasks. I've tried planning ahead for the day in Outlook by filling up the day or week with blocks of time that are colour coded by project, but the various pressures of project work, unit coordination, short notice meetings, requests for help from colleagues, etc. mean that by the end of the day the plan has completely changed.

## Sketch notes

Since I've been trying to do more [sketch-noting](https://www.jetpens.com/blog/sketchnotes-a-guide-to-visual-note-taking/pt/892) [@sketchnotehandbook] in meetings, planning sessions and seminars I've come to carry around a bevy of coloured pens, a fountain pen, pencils and eraser, ruler and lining pens. I don't sketch everything, but it's certainly been a good way to stop my mind wandering and to focus not on transcribing every word said but on distilling ideas quickly using a combination of quick sketching and more traditional note taking. Once the information's down and there's some time for it in either a break, a changeover, or question and answer time, I'll reorganise the words and pictures on the page in pencil before committing it all with ink.

This is usually done in one of a number of Rhodia notepads ([orange No 16, thanks](https://rhodiapads.com/collections_orange_16.php)) which are kept separate by project: Reef, Jaguars, ILAQH, Impro (one per year), Seminars, Research Planning, Japan, and an A4 one for my Dengue work. Separating everything out like that has meant that things don't get lost in a sea of disconnected topics where I have to either colour code every page or use coloured tabs that stick out the side for "easy" access.

## Bulleting

So the bullet journal seems well within my capabilities. You use pages as you need them, adding to the index page as you go, so there's very little pre-planning of what the end result will be. So if you struggle to fit everything into a pre-defined space for each day, week, and month in a traditional diary, no need to worry. Tasks get marked off as they're done, and at the end of the week you can carry an incomplete item on to the next week's page or bring it into the Future Log after your index page. There's a huge amount of variety in how you manage things and do up your pages. At first glance, it seems that a lot of people are putting Pinterest style inspirational quotes in calligraphic lettering with pastel colours. But then the person I first saw bullet journalling seems to leave the pages very spartan with lots of white space in between, so it is certainly possible to focus more on the content with a simple layout.

## Blogging

Time was, in the 1990s, you used a journal to jot down your thoughts. Then we all got Geocities websites where we wrote bad poetry and put up low resolution pictures of our favourite celebrities, we self-published our Stargate fan fiction on Livejournal if we wanted a community, or pushed out our thoughts on the local breakfast cafe scene on Blogger. Everyone moved to Wordpress or Squarespace when it came time to use a content management system, and now there's a plethora of systems like [ghost](https://ghost.org/), [Hugo](https://gohugo.io/) and [Jekyll](https://jekyllrb.com/) to choose from.

Academic blogging, at least in statistics, seems to be equal parts early career researchers looking to distinguish themselves, senior professors wanting to engage with people outside their regular research family, and package developers showing what they've got. For me, it's a way to keep track of what I'm working on and remind myself that I am making progress on projects and getting my work out there.

## The best of both worlds

For the less public journal, the time management one, I've decided that instead of full page spreads with artistically written month names and floral borders, each month will start with a grid calendar in the lower half of the page, below a heading one quarter of the day down the page and written in letting that my Year 10 Graphics teacher would be proud of. Around the month heading I'll be sketching notable achievements and adding some colour. So for March so far we've got a smoke-enveloped particulate agglomerate to represent the UPTECH paper and a two point perspective box representation of the Brisbane Powerhouse for the Brisbane Comedy Festival (in which I've currently performed twice).

I'm not sure that I'll be posting screenshots for accountability, but it'll certainly be good to have a way of tracking (for both my personal and professional life) tasks, day to day mood, upcoming events and recent achievements that makes me want to fill it out. Blogging can be kept for bragging about publications, putting thoughts down about educational philosophy, and posting about academic visits.

## References