---
title: A few wins on papers
author: Sam Clifford
date: '2018-03-16'
slug: a-few-wins-on-papers
categories: ["research",  "aerosol science", "uptech", "reef"]
bibliography: ../resume.bib
csl: ../chicago-author-date.csl
link-citations: yes
hasMath: true
---

## Air pollution

The main UPTECH paper is now published, so go and feast your eyes on our conclusions regarding the influence of traffic based air pollution on systemic inflammation [@uptechmain]. We adjusted for PM<sub>2.5</sub> and NO<sub>2</sub> in our model, as well as a range of common home confounders. There's still more to come from the UPTECH work; I'm currently working with a PhD student on the questionnaire data and looking at linking a bunch of health outcomes to multiple exposure outcomes using some multiple correspondence analysis with [FactoMineR](https://cran.r-project.org/web/packages/FactoMineR/index.html), and we are looking at doing clustering with categorical variables using some of the functions from [cluster](https://cran.r-project.org/web/packages/cluster/).

A paper on personal sampling of air pollution and subsequent exposure assessment has been submitted to Environment International [@airbeam]. This one's about monitoring adults as they go about their week at home, work, outdoors and commuting. It follows some of the approaches we took with earlier research [@mandanantpaper; @emacpaper] with a new technology. We also compare the home exposure to home characteristics, with a questionnaire a little less burdensome than the one in @uptechmain.

The work on this one involved writing and rewriting a bunch of code in collaboration with a few of the co-authors. It certainly made me think more about the readability of my own code. While not everyone learns the tidyverse approach from the get go, I think it does make for clearer code once you wrap your head around the chain of `%>%` pipes that us tidyverts tend to love using. Certainly I've started using the [forcats](https://cran.r-project.org/web/packages/forcats/index.html) package more often, which means never having to touch [plyr](https://cran.r-project.org/web/packages/plyr/index.html) as much as I liked the `mapvalues()` and `revalue()` functions.

I've also got a draft sitting in my inbox for a paper I've been involved with writing for a few years, applying some machine learning and statistical approaches to variable selection in land use regression. I'll be happy when this one's done, as a lot of work went into the writing of code to do some least angle regression with custom rules for variable inclusion. This modelling is the reason I wrote [mgcv.helper](https://github.com/samclifford/mgcv.helper), as I needed to calculate variance inflation factors and extract confidence intervals from a generalised additive model [@mgcv.helper].

## Reef

The paper on the citizen science experiment we did on the reef project has been accepted for publication after doing some reviews and adding more on the methodology [@reefaesthetics]. This was a nice bit of work that I was heavily involved with, designing the stratified random sampling of images to present to participants and writing data collection forms in R Markdown so that we had randomised booklets ready to go. Modelling was done with Bayesian hierarchical models to look at what members of the public, experienced divers and marine scientists each considered as an aesthetically pleasing reef, and eliciting explanations for their reasoning. 

Work continues on the main modelling paper for coral cover across the reef, with collaborators having finished building the new model with more covariate data available to us than went into the report we wrote for the project. Once the predictions are finalised the paper's results and discussion will be quickly done and it can be submitted. Again, this paper was a lot of my work from 2016 and so even though the project's come to an end there's always work writing up the research aspect of the project and getting the scientific recognition of the work.

## Other work

I got involved with some functional data analysis for sports training data a few months ago. The paper [@bernard] has been through a few rounds of revisions and is now back with the journal. It's been fun working on some data far outside my normal context. Bernard's done a good job learning more about semi-parametric regression techniques and functional data analysis.

## References