---
title: Maths in science
author: Sam Clifford
date: '2018-03-29'
slug: maths-in-science
categories: ["teaching", "research"]
bibliography: ../resume.bib
csl: ../chicago-author-date.csl
link-citations: yes
hasMath: true
---

I've been doing a lot of reading recently about the role of mathematics in a variety of scientific fields. As SEB113 is always on the move, we need to think about how to best support the needs of science students who are starting out their university studies. Part of this includes our diagnostic test to help them assess their needs, but a lot of it also thinking about what they need to work as a professional scientist and how to prepare them for their second year of study. With limited amount of space in a science degree for non-science units, it's important to make the most of the time we have with students and set them up for future success.

Feedback from students at the end of semester always includes comments about how SEB113 was the most difficult unit of the semester but also the most rewarding, so perhaps we're doing the right thing. There are also comments about how it was more difficult than they expected and they weren't overly fond of having to learn software to do their analysis. Student preparedness has been a big focus of redesigning SEB113 over the years, so we may need to adjust the expectations that we have of incoming students and make clearer what expectations they can have of the degree.

We want to make sure that students are at least prepared for their work as graduate scientists rather than being so scared that they avoid learning the skills they need to be competent scientists [@ecrecology]. The Australian Government does not provide any recommendations for improving the mathematical literacy of science graduates in Australia beyond improving teachers' mathematical capabilities [@isa2017], which is unfortunate. Ensuring access to highly trained science teachers is one thing, but if students aren't taking mathematics at the advanced and intermediate levels then they'll never have exposure to the topics they need.

## Decline in mathematics at school

There's been a marked decrease in the number of students taking advanced level mathematics at high school [@quteprints73153], with many dropping down to intermediate level, and then students dropping from intermediate down to beginner level. The Australian Academy of Sciences recommends in its decadal plan that intermediate mathematics be reintroduced as a prerequisite for all science, engineering and commerce degrees [@aas2025]. There's probably a feedback mechanism at play here where a drop in mathematics preparedness has been compensated for at the university level by reducing entry requirements into engineering, science and other quantitative courses. As a result of this, students are probably getting the idea that they don't *need* to study mathematics to get into a quantitative degree. Once they're at university, lecturers have to work hard to make sure that they've got the skills needed to get through their degrees. Accreditation and student progress therefore become competing goals, and universities have to decide what the level of mathematics is that students can pass out of the degree with.

## Physics and Chemistry

The Australian Institute of Physics' [accrediation guidelines](http://aip.org.au/accreditation/AIPAccreditationRegs2013-17updatedFeb2018/) state that "a three year degree program should include appropriate problem solving skills in Pure and/or Applied Mathematics including Differential Equations, Vector Analysis, Linear Algebra and Complex Analysis". Physics has always been the most mathematical of the sciences, but timing of calculus education at university poses challenges for determining when certain topics, such as electromagnetism and dynamics, can be taught with sufficient mathematical rigour.

The Royal Australian Chemical Institute's report on the future of chemistry [@raci2005] somewhat predates the concept of the STEM revolution and the slide in high school advanced mathematics enrolments and degree pre-requisites was in its infancy. As such, it does not make recommendations in its report about improving mathematics outcomes, although its current [guide to studying chemistry at university](https://www.raci.org.au/education/university-and-beyond/studying-chemistry-at-university) makes reference to an expectation that students will continue to develop "strong mathematical and numerical ability", and non-transferable skills including:

* analytical and problem-solving - examining and interpreting results and making evaluations based on limited information
* IT and technology - understanding and using computer software/models, processing data, using spreadsheets, word-processing and internet communication

The American Chemical Society's accreditation guidelines require that "Certified graduates must complete course work equivalent to two semesters of calculus and two semesters of physics with laboratory. The Committee strongly recommends a calculus-based physics curriculum and study of multivariable calculus, linear algebra, and differential equations" [@acs2015]. That's certainly a lot of mathematics for a three year undergraduate degree in Australia, so embedding mathematical topics at appropriate points in the Chemistry major units is probably the best way to deal with this.

## Life sciences

Studies of graduate outcomes [@ecrecology] and indicate that American ecology graduates wanted a more quantitative structure to their degree. In its review of important skills [@usgsstats], the US Geological Survey considered the following topics should be completed by the end of an undegraduate degree in wildlife biology:  

* Introductory probability and statistics
* Probability and mathematical statistics
* Theory of linear models
* Sampling methodology
* Experimental design
* Applied regression analysis
* Calculus

For those students going on to study at a Masters level, the USGS also recommends students consider linear algebra, a detailed study of differential equations, time series statistics, spatial statistics, stochastic processes, multivariate statistics, and survival analysis.

Statistics as a post-calculus topic is endorsed by @ellisondennis, who argue that statistical literacy comes from an understanding of the mathematics behind the statistical techniques, through an appreciation of model building and numerical techniques for solving non-standard problems rather than hand calculuation for grossly simple problems. @whitecalculus, cited by @ellisondennis, makes the case for students of ecology studying calculus, particularly as it leads to an improvement in rigour for mathematical thinking, which is particularly important for defining a goal and then developing, implementing and assessing a management plan to meet said goal.

Apart from calculus as a tool for understanding statistics, calculus is also a tool for modelling relationships in physical systems such as population dynamics [@ellisondennis]. Two good resources are @Gotelli and @gotelli2013primer which respectively cover key quantitative topics in mathematical modelling and statistics for ecology. With the demand for more mathematics-heavy ecology education from graduates [@ecrecology], a first semester calculus-based course designed around mathematical methods for life sciences students could run parallel to a more traditional calculus course for physicists.

@pmid20810962 outlines a course structure at the University of Arizona that has students study statistics after calculus, learning R to do data analysis beyond the calculation of summary statistics and simple hypothesis tests. The course is broken up into four components:

* Organizing and Collecting Data
* Introduction to Probability
* Estimation Procedures
* Hypothesis Testing

There's absolutely a paper in this work with the diagnostic and preparing for future study. With a few cohorts having gone through the entire science degree, I'd be very interested to do some analysis of the relationship between grades in SEB113 and grades in second year quantitative units. We might even be able to model outcomes based on how well students did in individual pieces of assessment based on the topic being assessed.