---
title: Research
author: Sam Clifford
date: 2011-10-10
---

Sam's current research work involves building spatio-temporal statistical models of air quality as part of ILAQH's projects "Ultrafine Particles from Traffic Emissions & Children's Health" ([UPTECH](http://www.ilaqh.qut.edu.au/Misc/UPTECH%20Home.htm), ARC Linkage LP0990134) and "Revolutionising protection against air pollution" (ARC Discovery DP150101828). These models are developed using Generalised Additive Model with splines, and Bayesian hierarchical models, and explain how differences in air quality can be attributed to local meteorology, daily and weekly trends and location as well as what their health impact are. His Postdoctoral Fellowship position involves developing and applying Bayesian statistical models for various aerosol science topics from the fields of chemistry, physics, microbiology and epidemiology. He has travelled to Helsinki, Finland in July 2011 to collaborate on descriptive and forecasting models for air quality, Braunschweig, Germany in August 2015 to collaborate on personal exposure models, and Milan, Italy in September 2015 to collaborate on stochastic PDE models of Chlamydia dynamics. Since attending the 8th [Workshop on Bayesian Nonparametrics](http://bnpworkshop.org/), Sam has developed an interest in Bayesian nonparametric methods and continues to look for an excuse to use them in his future work.