---
title: Publications
author: Sam Clifford
date: 2011-10-11
---

## Papers

### Preprints

[QUT ePrints](http://eprints.qut.edu.au/view/person/Clifford,_Sam.html) ' [arXiv](http://arxiv.org/a/clifford_s_1) ' [Google Scholar](https://scholar.google.com.au/citations?user=KbrnxeoAAAAJ&hl=en) ' [ORCID](http://orcid.org/0000-0002-3774-3882)

### 2016

R. Luscombe et al., "A blended learning model for first year science student engagement with mathematics and statistics", HERDSA Conference, Abstract accepted, full paper submitted. T. Salthammer et al., "Children's well-being at schools: complex interdependency between air pollution, temperature and underlying energy considerations", Environment International, submitted. H. Salonen et al., "Endotoxin levels and contribution factors of endotoxins in resident, school and office environments - A review". In prep. L. Morawska, M. Mazaheri, G. Buonanno, S. Clifford, F. Fuoco, T. Wangchuk, "Comparative personal exposure assessment of school children to particle number concentrations in Australia, Italy, and Bhutan". Indoor Air 2016\. Submitted.

### 2015

H. Salonen, C. Duchaine, M. Mazaheri, **S. Clifford**, S. Lappalainen, K. Reijula, L. Morawska, "Airborne viable fungi in school environments in different climatic regions - a review", [_Atmospheric Environment_ 104, 186-194](http://www.sciencedirect.com/science/article/pii/S135223101500014X). M. G. Falk, C. L. Alston, C. A. McGrory, **S. Clifford**, E. A. Heron, D. Leonte, M. Moores, C. D. Walsh, A. N. Pettitt, K. L. Mengersen, "Recent Bayesian approaches for spatial analysis of 2-D images with application to environmental modelling", [_Environmental and Ecological Statistics,_ 22 (3): 571-600](http://link.springer.com/article/10.1007/s10651-015-0311-1). Wafaa Nabil Ezz, M. Mazaheri, P. Robinson, G. Johnson, **S. Clifford**, C. He, L. Morawska, G. B. Marks, "Ultrafine Particles from Traffic Emissions and Children's Health", [_International Journal of Environmental Research and Public Health_, 12 (2): 1687-1702](http://www.mdpi.com/1660-4601/12/2/1687). S. Stevanovic, B. Miljevic, P. Madl, **S. Clifford**, Z. Ristovski, "Characterisation of a commercially available thermodenuder and diffusion drier for ultrafine particles losses", [_Aerosol and Air Quality Research_, 15 (1): 357-363](http://aaqr.org/Doi.php?id=30_AAQR-13-12-TN-0355). H. Salonen, C. Duchaine, M. Mazaheri, **S. Clifford**, L. Morawska, "Airborne culturable fungi in naturally ventilated primary school environments in a subtropical climate", [_Atmospheric Environment,_ 106, 412-418](http://www.sciencedirect.com/science/article/pii/S1352231014005822). Ehsan Majd Faghihi, Darren Martin, **Samuel Clifford**, Grant Edwards, Congrong He, Christof Asbach, and Lidia Morawska, "Are there generalizable trends in the release of airborne synthetic clay nanoparticles from a jet milling process?", [_Aerosol and Air Quality Research_, 15 (2), 365-375](http://aaqr.org/Doi.php?id=1_AAQR-14-06-OA-0124). L. Toms, M. Mazaheri, S. Brommer, **S. Clifford**, D. Drage, J. Mueller, P. Thai, S. Harrad, L. Morawska, F. Harden, "Polybrominated diphenyl ethers (PBDEs) in dust from primary schools in South East Queensland, Australia", [_Environmental Research_, 142, 135-140.](http://www.sciencedirect.com/science/article/pii/S0013935115001826) E. R. Jayaratne, **S. Clifford**, L. Morawska, "Atmospheric Visibility and PM10 as Indicators of New Particle Formation in an Urban Environment", [_Environmental Science & Technology_](http://pubs.acs.org.ezp01.library.qut.edu.au/doi/abs/10.1021/acs.est.5b01851) 49 (21): 12751-12757. T. Wangchuk, M. Mazaheri, **S. Clifford**, M. Dudzinska, C. He, G. Buonanno, L. Morawska, "Children's personal exposure to air pollution in rural villages in Bhutan", [_Environmental Research_, 140, 691-698](http://www.sciencedirect.com/science/article/pii/S0013935115001814). Md Mahmudur Rahman, Mandana Mazaheri, **Sam Clifford**, Lidia Morawska, "Beyond traffic emissions: non-traffic sources of ambient urban ultrafine particles", _Atmospheric Environment_, submitted.

### 2014

**Samuel Joseph Clifford**, Mandana Mazaheri, Rohan Jayaratne, Megat Azman Megat Mokhtar, Fernanda Fuoco, Giorgio Buonanno, Lidia Morawska, "Estimation of inhaled ultrafine particle surface area dose for urban environments", [_ANZIAM Journal_ 55: C437-C447](http://journal.austms.org.au/ojs/index.php/ANZIAMJ/article/view/7819). M. Mazaheri, **S. Clifford**, R. Jayaratne, M. A. Megat Moktar, Fernanda Fuoco, G. Buonanno, L. Morawska, "School children's personal exposure to ultrafine particles in the urban environment", [_Environmental Science & Technology_, 48 (1): 113-120](http://pubs.acs.org/doi/abs/10.1021/es403721w) F. Salimi, Z. Ristovski, M. Mazaheri, R. Laiman, L. R. Crilley, C. He, **S. Clifford**, L. Morawska, "Assessment and Application of Clustering Techniques to Atmospheric Particle Number Size Distribution for the Purpose of Source Apportionment", [_Atmospheric Chemistry and Physics_ 14: 11883-11892](http://www.atmos-chem-phys.net/14/11883/2014/acp-14-11883-2014.html). R. Laiman, C. He, M. Mazaheri, **S. Clifford**, F. Salimi, L. Crilley, M. A. Megat Mokhtar, L. Morawska, "Characteristics of ultrafine particle sources and deposition rates in primary school classrooms", [_Atmospheric Environment_, 94: 28-35](http://www.sciencedirect.com/science/article/pii/S1352231014003604). R. Laiman, C. He, M. Mazaheri, **S. Clifford**, F. Salimi, L. Crilley, M. A. Megat Moktar, L. Morawska, "The effect of outdoor sources on indoor particle concentrations in primary schools", submitted.

### 2013

B. Mølgaard, W. Birmili, **S. Clifford**, A. Massling, K. Eleftheriadis, M. Norman, S. Vratolis, B. Wehner, J. Corander, K. Hämeri and T. Hussein. "Evaluation of a statistical forecast model for size-fractionated urban particle number concentrations using data from five European cities", _Journal of Aerosol Science_, 66: 96-110\. [ScienceDirect](http://www.sciencedirect.com/science/article/pii/S0021850213001833). F. Salimi, M. Mazaheri, **S. Clifford**, L. Crilley, R. Laiman, L. Morawska, "Spatial variation of particle number concentration in school microscale environments and its impact on exposure assessment", [_Environmental Science & Technology_, 47: 5251-5258](http://pubs.acs.org/doi/abs/10.1021/es400041r). H. Salonen, C. Duchaine, V. Létorneau, M. Mazaheri, **S. Clifford**, L. Morawska, "Endotoxins in indoor air and settled dust in primary schools in a subtropical climate", [_Environmental Science & Technology_, 47 (17), pp 9882-9890](http://pubs.acs.org/doi/abs/10.1021/es4023706). **S. Clifford**, B. Mølgaard, S. Low Choy, J. Corander, K. Hämeri, K. Mengersen, T. Hussein, "Bayesian semi-parametric forecasting with penalised splines and autoregressive errors", [arXiv](http://arxiv.org/abs/1207.0558)

### 2012

**S. Clifford**, S. Low Choy, M. Mazaheri, F.Salimi, K. Mengersen, L. Morawska, "A Bayesian spatio-temporal model of panel design data: airborne particle number concentration in Brisbane, Australia", [arXiv](http://arxiv.org/abs/1206.3833)

### 2011

**S. Clifford**, S. Low Choy, T. Hussein, K. Mengersen, L. Morawska, "Using the Generalised Additive Model to model the particle number count of ultrafine particles", [_Atmospheric Environment_ 45 (2011): 5934-5945](http://www.sciencedirect.com/science/article/pii/S1352231011004766),

## Conference papers

<span style="line-height:1.714285714;font-size:1rem;">Buonanno, G., Mazaheri, M., Fuoco, F.,</span> **Clifford, S**<span style="line-height:1.714285714;font-size:1rem;">., Russi, A., Morawska, L., Vigo, P., Jayaratne, R., & Viola, A. (2013) Alveolar dose comparison of ultrafine particles for Australian and Italian children. In 12th Biennial National Conference "Healthy, Wealthy and Safe" Macquarie Park, Sydney,</span> [Metrology Society of Australia 2013 conference](http://metrology.asn.au/conferences.html)<span style="line-height:1.714285714;font-size:1rem;">, 15 - 17 October 2013\.</span> [ePrints](http://eprints.qut.edu.au/62902/)<span style="line-height:1.714285714;font-size:1rem;">.</span> **S. Clifford**, M. Mazaheri, E. R. Jayaratne, M. A. Megat Mokhtar, F. Fuoco, G. Buonanno and L. Morawska, "Estimation of inhaled ultrafine particle surface area dose in urban environments", Proceedings of the Engineering Mathematics and Applications Conference 2013. **S. Clifford**, K. Mengersen, S. Low Choy, M. Mazaheri, L. Morawska, A method for non-parametric cluster analysis of the health impacts of air quality, ISIAQ [Healthy Buildings 2012](http://hb2012.org)

## Book chapters

**S. Clifford** and S. Low Choy, "Bayesian splines." In [_Case studies in Bayesian statistical modelling and analysis_](http://www.wiley-vch.de/publish/en/books/bySubjectST00/bySubSubjectSTC0/1-119-94182-2/?sID=5hufm9igvb00pq7hk2gp3rj2e5), edited by C. Alston, K. Mengersen and A. Pettitt, 197-220\. John Wiley and Sons, 2012.

## Other conference items

L. Morawska, M. Mazaheri, G. Buonanno, **S. Clifford**, F. Fuoco, T. Wangchuk, "Comparative personal exposure assessment of school children to particle number concentrations in Australia, Italy and Bhutan". Indoor Air; 2016 July 3-8; Ghent, Belgium. Abstract submitted. L. Morawska, L. Falcão, **S. Clifford**, D. Broday, "Forecasting of indoor air quality parameters". Indoor Air; 2016 July 3-8; Ghent, Belgium. Abstract submitted. L. Falcão, **S. Clifford**, L. Morawska, D. Broday, "Non-parameteric estimation of the influence of meteorology on indoor and outdoor air". Aerosols; 2016 April 20-26; Barcelona, Spain. Abstract submitted. M. Mazaheri, **S. Clifford**, and L. Morawska , "Inhaled particle surface area dose: stationary vs personal monitoring", European Aerosol Conference; 2015 September 6-11; Milan, Italy. **S. Clifford**, M. Mazaheri, B. Yeganeh, K. Mengersen, and L. Morawska , "Uncertainty in exposure estimates and imputation of missing aerosol data in an epidemiological study", European Aerosol Conference; 2015 September 6-11; Milan, Italy. M.M. Rahman, M. Mazaheri, **S. Clifford**, and L. Morawska, "Characterisation and sources of ultrafine particles in an inner city urban area", European Aerosol Conference; 2015 September 6-11; Milan, Italy. Jayan Karunasinghe, Luke Knibbs, **Sam Cliford**, Lidia Morawaska, Land use regression model for ultrafine particles in Brisbane. Asian Aerosol Conference; 2015 June 24-27; Kanazawa, Japan. Morawska, L., Mazaheri, M., **Clifford, S.**, Salimi, F., Laiman, R. and Crilley, L. Indoor air pollution sources and exposures in primary schools: UPTECH Synthesis (Oral Presentation). Indoor Air 2014, Hong Kong, 7-12 July 2014. M. Mazaheri, **S. Clifford**, E. R. Jayaratne, M. A. Megat Mokhtar, F. Fuoco, G. Buonanno, L. Morawska, "Alveolar dose of ultrafine particles for children in urban environments". European Aerosol Conference; 2013 September 1-6; Prague, Czech Republic. [Abstract](http://eac2013.cz/EAC%20abstracta/Indoor%20and%20Working%20Place%20Aerosols/Mazaheri-Mandana_Indoor%20and%20Working%20Place%20Aerosols_20130218-071422_8005733027.pdf). **S. Clifford**, K. Mengersen, S. Low Choy, L. Morawska, [Spatio-temporal modelling of particle number concentration](http://samcliffordinfo.files.wordpress.com/2011/10/8bnpposter.pdf). 8th Workshop on Bayesian Non-parametrics; 2011 June 26-30; Veracruz, Mexico. H. Salonen, L. Knibbs, C. Ranasinghe, **S. Clifford**, P. Grzybowski, S. Bell, C. He, M. Hargreaves, L. Morawska, [Monitoring airborne fungi and bacteria in a major teaching hospital, Brisbane, Australia](http://icoh.confex.com/icoh/2012/webprogram/Paper7805.html). 30th International Congress on Occupational Health; 2012 March 18-23; Cancun, Mexico. **S. Clifford**, S. Low Choy, K. Mengersen, L. Morawska, [Bayesian spatio-temporal modelling of ultrafine particle number concentration from a panel design](http://bayesian.org/node/2915), ISBA World Meeting 2012

## Interviews

"Dust Storms". [Totally Wild - S2, E37 (20 February 2012) Channel Ten (Australia)](http://ten.com.au/video-player.htm?movideo_p=41457&movideo_m=162536). "Dust Storm". [Scope - Dirty Science, (29 March 2012) Channel Ten (Australia)](http://ten.com.au/video-player.htm?movideo_p=41452&movideo_m=172784). (begins 0:54) Interview - Aerosol science and statistics. [Smart Enough to Know Better - Episode 40](http://smartenough.org/index.php?start=70). Interview - International Year of Statistics. ABC local radio (10 April 2013).