---
title: A mostly Fin(n)ish[ed] paper
author: Sam Clifford
date: 2012-05-09
tags: ["aerosols","blog","Blog","finland","git","isba","matlab","matt wand","nonparametrics","papers","programming","qut","statistics"]
---

The paper I started with some collaborators in Finland ([Bjarke Mølgaard](https://tuhat.halvi.helsinki.fi/portal/en/persons/bjarke-moelgaard(74a8081d-a379-4e4b-9aff-e9b85bc98c78)/publications.html), [Jukka Corander](http://www.rni.helsinki.fi/~jic/), [Kaarle Hämeri](http://www.atm.helsinki.fi/~khameri/),  [Tareq Hussein](https://tuhat.halvi.helsinki.fi/portal/en/persons/tareq-hussein(3aacf8e7-f431-41b0-9303-1abaf1897bf7)/publications.html?page=5&rendering=vancouver)) almost a year ago is nearly done. It's been nearly done a few times, but now all that remains is to do a little bit of model choice regarding the separability of the effects of meteorology on ultrafine particle number concentration. We've been using git to send the paper and code back and forth (well, Bjarke and I have) and I've found that to be a really simple way of collaboratively writing code and a paper. To see the changes made, one need only look at the commit details. Much nicer than using tracked changes in Word and emailing a bunch of versions of the same file back and forth and trying to do complicated merges of changes. I am really looking forward to submitting this paper, as it's probably the most methodological work I'll get out of my PhD (the other papers are largely applications of some novel techniques to the UPTECH project's data). It's quite a nice blending of the [work done by the Finnish authors previously](https://tuhat.halvi.helsinki.fi/portal/en/publications/forecasting-sizefra(9c6ae07d-af34-4909-a4f9-d758bc7a4795).html)  [1] as part of Bjarke's PhD and some of the ideas in my first paper [2]. While I don't know that it will totally revolutionise atmospheric modelling (in the way that I'm sure we all hope it will), it's quite a nice technique that increases the flexibility of the Generalised Additive Model and hopefully encourage anyone interested in doing Bayesian modelling with the GAM to stop using [Matt Wand](http://www.uow.edu.au/~mwand/)'s WinBUGS approach [3, 4]. To be clear, I find GAMs in WinBUGS particularly cumbersome to code given that WinBUGS doesn't deal with matrix operations very well and the use of P-splines requires a lot of matrix operations. Having said that, though, Wand's code is a nice intro to Bayesian splines where you don't have to write your own MCMC sampler. I just think it has some limitations that are not easily overcome. I'd like to present this to a statistics conference but it wasn't anywhere near ready enough to demonstrate at ISBA 2012 when I was submitting an abstract. [1] B. Mølgaard, T. Hussein, J. Corander, K. Hämeri, Forecasting size-fractionated particle number concentrations in the urban atmosphere, Atmospheric Environment, Volume 46, January 2012, Pages 155-163, ISSN 1352-2310, 10.1016/j.atmosenv.2011.10.004\. [ScienceDirect](http://www.sciencedirect.com/science/article/pii/S1352231011010491) [2] S. Clifford, S. Low Choy, T. Hussein, K. Mengersen, L. Morawska, Using the Generalised Additive Model to model the particle number count of ultrafine particles, Atmospheric Environment, Volume 45, Issue 32, October 2011, Pages 5934-5945, ISSN 1352-2310, 10.1016/j.atmosenv.2011.05.004. [ScienceDirect](http://www.sciencedirect.com/science/article/pii/S1352231011004766) [3] C. M. Crainiceanu, D. Ruppert. M. P. Wand, Bayesian Analysis for Penalized Spline Regression Using WinBUGS, [Journal of Statistical Software, Volume 14, Issue 14, September 2005](http://www.jstatsoft.org/v14/i14/). [4] J. K. Marley, M. P. Wand, Non-Standard Semiparametric Regression via BRugs, [Journal of Statistical Software, Volume 37, Issue 5, November 2010](http://www.jstatsoft.org/v37/i05). P.S. I apologise for the awful pun, but [Shaun Micallef](http://en.wikipedia.org/wiki/The_Micallef_P(r)ogram(me)) has been on my mind recently.