---
title: Revision, revised
author: Sam Clifford
date: 2012-07-15
tags: ["bayesian statistics","blog","Blog","gaussian process","seminar","statistics","video lecture"]
---

I just quickly want to plug the videolectures.net website, as it's a great repository of talks about a wide range of topics. In particular, I want to plug the following two reviews of Bayesian statistics:

*   Christopher Bishop (Microsoft Research) - [Introduction to Bayesian Inference](http://videolectures.net/mlss09uk_bishop_ibi/) (MLSS 2009)
*   Carl Edward Rasmussen (Max Planck Institute) - [Bayesian Inference and Gaussian Processes](http://videolectures.net/mlss07_rasmussen_bigp/) (MLSS 2007)

The first, three hours long, gives a good overview of what Bayesian stats is, conceptually, and introduces a few key terms and some examples. The second one, five hours long, goes deeper into the difference between frequentist and Bayesian statistics and builds towards the use of Gaussian process models, a very important class of models that have a wide variety of applications. If you've got eight hours to kill, even if it's spread over a few weeks, these appear to form a very good introduction to Bayesian statistics which progresses logically and introduces what's needed when it's needed.