---
title: Charts and infographics
author: Sam Clifford
date: 2012-05-29
tags: ["blog","Blog","brag","data","ilaqh","latex","qut","science","statistics","visualisation"]
---

One of my supervisors, Sama Low Choy, is always up for a chat about the role of visualisation in statistics and data analysis. An acolyte of [Tufte](http://www.edwardtufte.com/tufte/), Sama is quite passionate about appropriate methods of presenting data. 3D pie charts, needless to say, are public enemy number one. We were having a chat this afternoon about how [a friend of mine](http://conidialcoleopticide.wordpress.com/) who's about to start a Masters in biology/statistics is a bit of a nerd when it comes to the presentation of data and copy. Talk turned to how easy it is to use LaTeX and how there's a need for better visualisation in scientific results (something I've talked to some of my ILAQH colleagues about at length). Infographics are quite a popular thing at the moment, despite not always being particularly informative nor warranted, and I mentioned [a blog about the process that the New York Times crew go through when developing infographics](http://chartsnthings.tumblr.com) and other visualisation tools. Sama has forwarded me an email containing some of her favourite links that deal with the field of "data journalism".

> The Times in US provide some inspiration: [http://blog.visual.ly/20-great-visualizations-of-2011](http://blog.visual.ly/20-great-visualizations-of-2011)/ Even on a topic that some science & engineerings students may become engaged with: [http://blog.visual.ly/best-beer-infographics-and-data-visualizations](http://blog.visual.ly/best-beer-infographics-and-data-visualizations) Someone else's selection of highlights from their Infographics [http://www.smallmeans.com/new-york-times-infographics](http://www.smallmeans.com/new-york-times-infographics) Here is a link to a website about a new (free) handbook on data journalism: [http://datadrivenjournalism.net/news_and_analysis/A_peek_inside_the_Data_Journalism_Handbook#When:07:28:52Z](http://datadrivenjournalism.net/news_and_analysis/A_peek_inside_the_Data_Journalism_Handbook#When:07:28:52Z) Here's a link to some videos (showing some software, doing some intuitive roll-up roll-down exploration & aggregation of data): [http://www.panopticon.com/videos](http://www.panopticon.com/videos)

You might also enjoy [these videos of Amanda Cox](http://infosthetics.com/archives/2011/12/amanda_cox_talks_about_developing_infographics_at_the_new_york_times_graphics.html), a woman behind some of the more innovative visualisation pieces at the NYT, talking about the processes of making good quality visualisations.