---
title: Credibility of information given font choice
author: Sam Clifford
date: 2012-08-12
tags: ["atlas","blog","Blog","cern","communication","latex","publishing","science communication"]
---

Thanks to the [Monkey Cage blog](http://themonkeycage.org/blog/2012/08/11/potpourri-80) (a very good read if you're a fan of statistics and politics as I am) I've come across [an opinion article](http://opinionator.blogs.nytimes.com/2012/08/08/hear-all-ye-people-hearken-o-earth/) on the New York Times' page that discusses whether the font or handwriting style that is used to convey information has any impact on whether we believe that information. It's worth a read, as is the follow up and the preceding article (an essay and a quiz). There's a lot of really interesting stuff in there, but one that really leaps out is the ATLAS slides from the presentation about the Higgs Boson. Comic Sans is used to convey fun, light-heartedness, etc. and as far as I'm concerned it simply does not belong in academia. The article goes on to do some analysis of the previous article's quiz and shows that Baskerville is the font with the most _gravitas_. Rather than having me summarise the article here (it's quite long) it's probably better to just go and read it. If you've ever wondered about whether you should use a particular font (personally, Times New Roman is boring and Cambria is ugly) to convey a particular feeling in your article then this is food for thought. I use LaTeX to write papers and read a lot of papers typeset in LaTeX. As such, my eyes tend to see a lot of [Computer Modern](http://en.wikipedia.org/wiki/Computer_Modern), which has a bit of a reputation as being an academic font. I wouldn't publish a school newsletter in Computer Modern, of course, but for "serious" writing, CM is it.