---
title: Minimal version control lesson - use it
author: Sam Clifford
date: 2012-07-31
tags: ["blog","Blog","git","programming","R"]
---

[From the Win-Vector blog](http://www.win-vector.com/blog/2012/07/minimal-version-control-lesson-use-it/),

> There is no excuse for a digital creative person to not use some sort of version control or source control. In the past disk space was too dear, version control systems were too expensive and software was not powerful enough; this is no longer the case. Unless your work is worthless both [back it up](http://www.win-vector.com/blog/2009/06/public-service-article-back-up/) _and_ version control it.

This is probably the best advice I can give anyone about why using git is a good idea. There's no reason to take care of work that is not valuable. If you're doing any kind of research that requires writing, back it up and use version control (especially if you're coding). The above article gives a nice, simple introduction to using git without heading off into lengthy discussions about the role of branches and how to fork repositories. Given that I've been encouraging people in my group to move into using git and R this might be a good article to pass around.