---
title: A few things from today
author: Sam Clifford
date: 2012-08-16
tags: ["aerosols","bayesian statistics","bhutan","blog","Blog","christian robert","programming","qut","R","science","seminar","statistics"]
---

[Christian Robert](https://xianblog.wordpress.com/) is visiting my stats research group at the moment. This morning he spoke to our group's fortnightly meeting about a few issues in model choice and how to improve our Bayesian computation. The meeting was fairly well attended and was in fact [Luisa](http://conidialcoleopticide.wordpress.com/)'s first BRAG meeting. The model choice stuff was interesting and involved a discussion of Bayes factors, the BIC and DIC, and posterior predictive densities and checks. I'm not especially familiar with the Bayes factor approach (despite our group reading a paper about them recently) but did pick up the criticism from Robert that while the BIC is consistent with Bayes factors, it's not a very Bayesian approach and is a limited representation of the impact of the prior. There were some good little bits about the need to ensure that when using the BF to choose between nested models you don't end up using priors that are so diffuse that there's no concentration of support in the posterior. He also spoke briefly about the Kullback-Leibler Divergence and got into a discussion with Chris Strickland about model averaging with the BF to compare candidate models. Clearly I've got some reading to do. We didn't have much time to talk about improved mixing for MCMC but Robert did offer tempering as a way to come up with better proposals. The basic idea is that instead of using the posterior, π(θ)×f(x'θ), you look at {π(θ)×f(x'θ)}^α (for α << 1) to flatten out the posterior in order to allow a fuller exploration of the target distribution. This may end up giving you more density in the tails of the posterior (which is probably multidimensional) but the argument could be made (perhaps by Aad van der Vaart) that it's more important to have a vague posterior that better captures the truth than a very tight posterior CI around something which is wrong. Tempering is apparently Robert's "go to" trick when his MCMC is slowly mixing. I know Sama Low Choy, one of my supervisors, has mentioned it a few times. So I might try looking at it for the Finnish paper's successors. One of my aerosol science group's PhD students, Tenzin Wangchuk, gave his confirmation seminar today. Tenzin is with us for three months every year and spends the rest of his time in Bhutan. Tenzin's work will look at indoor air quality in rural Bhutan and what factors (e.g. cooking, outdoor air exchange, fuel types) influence the concentration of fine particles and gaseous pollutants. I had a few meetings with Tenzin last time he was here, where we discussed approaches to data analysis, and experimental design. Tenzin's a really nice guy; one of my favourite things about working at [ILAQH](http://www.ilaqh.qut.edu.au/) is the opportunity to meet people from around the world who have different experiences and interesting projects. Tenzin's work is similar to t[he studies ILAQH have done in Laos](http://onlinelibrary.wiley.com/doi/10.1111/j.1600-0668.2010.00679.x/full) but don't focus on the health aspect. It'll be interesting to see the results of his work. I'm also trying to get a beginners' R reading group up and running between ILAQH and BRAG. A few ILAQH members attended a two day course run by one of the PhD students in BRAG but I've really found the reading group structure to be quite useful for learning from a shared position of ignorance of, but interest in, a topic. I think the real strength of the model is that it encourages attendees to be self-reliant for their learning while still providing an environment for seeking help. If you don't do the readings and the work then it's very hard to keep up with what the group is doing and to participate in the discussion. So hopefully it discourages the kind of person who wants to sit back and have everyone else do the work (undergrad group assignments are the worst for this) or at least encourages them to do the work. I've got a few PhD students expressing interest so far, as well as one or two of the academics! I'll come along to the first few meetings to get the ball rolling, get everyone aware of each others' learning styles and backgrounds, give an overview of what R is and then give them a few resources and references to get started before leaving them to their own devices to study what they want to learn.