---
title: Thesis update
author: Sam Clifford
date: 2012-11-28
tags: ["blog","Blog","funding","ilaqh","qut"]
---

It feels like it's been a very long time since I posted a substantial update here. Last week was incredibly stressful and had me working on my thesis as well as on three other papers that I'm writing with colleagues here at ILAQH. My primary supervisor is back as of this week and it's going to be a huge push to get this thesis finished, which means not much time for other projects. Since importing papers into my thesis document and expanding my literature review and introduction these past few days my thesis document has grown from about 50 to about 160 pages. Of course, the page and word count is unimportant in the end; what matters is that I write good work that is viewed favourably by the panel. I realised that I hadn't announced it here but the [Centre for Air quality & health Research and evaluation (CAR)](http://www.car-cre.org.au/) has granted me a post-doctoral fellowship worth 75% of a full time equivalent load. This is about twice what I get as an APA(I) scholarship holder, lasts for a year, and will keep me fed and clothed while I work on a variety of papers regarding statistical modelling of air quality.