---
title: On to the next paper
author: Sam Clifford
date: 2012-04-11
tags: ["blog","Blog","code","matlab","papers","programming","science","statistics"]
---

I've just submitted the second paper of my PhD to my supervisors for what I hope to be a final round of feedback before we submit it. It comes in at just under twenty pages, which is what Annals of Applied Statistics sets as their usual maximum page limit. If there's more to add I can probably turn some of the more theoretical stuff into supplementary material. Once we submit I'll put the paper up on arXiv and link to it here so you can all have a look at how I think you should do hierarchical modelling in INLA for panel design data. Now that this paper's more or less out of the way it's time to go back to working on the paper that I've been working on with the Finnish team. It's been a huge coding project but now the code is at a stage where, more or less, Bjarke and I are happy with it and it's time to finalise the model we present as an example and write the analysis (the theory, discussion, etc. are mostly done). We still have to finalise where we're going to send it but my hope is that we don't have to pare away all the theory and end up sending it to an atmospheric science journal as an applied paper, because there has been an awful lot of work go into the modelling approach. I'm really looking forward to this one being done because it's been going for about nine to ten months and it's been on the backburner while I focussed on the INLA papers. It's a very neat method and I hope the community agrees. I'll also arXiv it and hope to release the code once the paper's published.