---
title: Ad hoc collaboration
author: Sam Clifford
date: 2012-06-05
tags: ["blog","Blog","brag","collaboration","git","google","ilaqh","nonparametrics","papers","programming","qut","R","statistics"]
---

Rbloggers have [announced the launch](http://www.r-bloggers.com/announcing-rpubs-a-new-web-publishing-service-for-r/) of [RPubs](http://www.rpubs.com/), a free service which makes it easy to publish code and analysis on the web. It's based on RStudio and the markdown package and looks like a great way for people to show analysis to co-workers who might not have R on their computers when you don't feel like writing a report. I really like this idea and might end up using it in my office to show what we can do with statistics. Another thing I've been thinking about is the potential to use an Apple TV and its [screen sharing](http://www.apple.com/au/appletv/airplay/) capabilities to do presentation work from iPhones, iPads and Mac computers. A lot of people in my office have iPhones, so an Apple TV hooked up to a HDMI screen (surely universities just leave these lying around) might be a good way to get a group of people to take some notes or share prepared slides with a small room of people. For example, if people had a PDF version of slides on their iPhones they could take control of the Apple TV and use their iPhone to flick through the slides, allowing everyone to stay in their seats and control the slideshow from their own device. I was excited by Google Wave when it first launched, as it combined a lot of what I liked about Gmail, Google Docs and Google Chat with an extension system, making it an incredibly powerful and flexible platform for collaborative work. Unfortunately it was released prematurely and died off after a flurry of uptake. Google Plus doesn't really make up for it, either. I really liked the idea of collaboratively writing a document and being able to add in a voting gadget to resolve whether a section should be included. I used it socially to determine the dates of picnics with friends, which was probably where most of my use was directed. Probably the best example of how useful I found it was in writing a manual of procedures with about ten other volunteers who would ask questions. As we answered the questions, we folded the answers into the main part of the document. This was much more useful than writing a static document and then having a separate email list for discussion, or using track changes in Microsoft Word to email around a huge document that kept on growing. I have high hopes for the internet in terms of _ad hoc_ collaboration, particularly academic collaboration. I find [GitHub](http://github.com/) really exciting because it allows me to work on a private project and then add a collaborator when they come on board. Once a project is finished and the paper published, that private repository can be made public and anyone can fork it and do with it what they will. If they're intrigued by what's been done, they could contact me and discuss what they've done and we can build a new project based on their fork of my work. With so much of my work being based on R or MATLAB and written up in LaTeX, I find this potential way of working quite sensible. Add in the fact that GitHub gives you a wiki system for each project and you've got a great tool at your disposal. A somewhat _ad hoc_ collaborative tool that I organised is the [wiki for QUT's Bayesian Non-parametrics reading group](https://wiki.qut.edu.au/display/npbayes/Home). This is a repository for the collective work of the group, including Q&A on the papers we're reading, notes from the meetings, a list of papers read, code chunks, links to videos explaining what we're working on, etc. It's been a really useful tool and I'd hope that others interested in the same work could use it as a resource for their own learning. There's a lot of really cool stuff out there. It's a matter of finding useful tools that don't have particularly high barriers to entry and allow non-experts to view expertly produced material (like on RPubs). The longer it's been since one was a student, the less likely one seems to be to adopt new workflow practices. I've suggested git to my supervisors as a good way for our groups to work but I have a feeling that none of them are interested enough in distributed version control to put the effort in to learning how to use them. So for now it's annotated PDFs or printed pages with scribbles on them rather than making the edits to a LaTeX source file and committing and pushing their changes to a shared repository.