---
title: Resubmission of Finnish paper
author: Sam Clifford
date: 2012-08-08
tags: ["arxiv","bayesian statistics","Blog","finland","open access","papers","publishing","science","statistics"]
---

I've spent a lot of my time since Healthy Buildings finished revising the semi-parametric forecasting paper. We had submitted to Annals of Applied Statistics but it was rejected. We got some very useful comments back from the reviewer, though, and I think it's a much stronger paper now. The reviewer encouraged us to rewrite the paper with a focus on the methodology rather than the application and submit it to a more theoretical journal. I have just submitted it to [Bayesian Analysis](http://ba.stat.cmu.edu/) (IF: 1.650), the official journal of [ISBA](http://bayesian.org), and uploaded the preprint to arXiv (where it will replace the [current version](http://arxiv.org/abs/1207.0558) in the next 24 hours). As an Open Access journal with a well-written LaTeX document class, Bayesian Analysis is a journal I can get behind. Some very good papers have appeared there and as Bayesian statistics continues to grow as a field (and ISBA as a society) I think we can expect to see BA really take off as a journal. So much of modern statistics is algorithms rather than proofs and making these available to people, particularly people who aren't academics, with freely available, peer reviewed papers will help improve the statistical capabilities of modern science.