---
title: Unfinnished business
author: Sam Clifford
date: 2012-08-30
tags: ["bayesian statistics","blog","Blog","brag","finland","inla","isba","journals","papers","publishing","qut","science","statistics"]
---

I've just heard from Kerrie Mengersen that the Finnish paper got rejected by BA for not being novel enough to publish there. So now I'm in a situation where I've got a paper which is too methodological for an applied stats journal (and far too methodological for an atmospheric science journal) and not a novel enough methodology for a journal as theoretical as BA. If BA don't think it's novel enough and it's not the first time this data's been published we'll struggle to get it into something like [JRSS B](http://www.rss.org.uk/site/cms/contentviewarticle.asp?article=876) (IF: 3.645), [JRS: Interface](http://rsif.royalsocietypublishing.org/) (IF: 4.402) or [PLoS One](http://www.plosone.org) (IF: 4.092). Our options, then, seem to be trying an Elsevier journal like [EMS](http://www.journals.elsevier.com/environmental-modelling-and-software/) (IF: 3.114) or [CSDA](http://www.journals.elsevier.com/computational-statistics-and-data-analysis/) (IF: 1.028), which I'm not keen to do, somewhere like [JSS](http://www.jstatsoft.org) (IF: 2.647) or a more applied journal like [JRSS C](http://onlinelibrary.wiley.com/journal/10.1111/(ISSN)1467-9876) (IF: 0.828, which is quite low). I'd like to put this in a statistics journal because I want to have a career as a statistician rather than just someone who can only work in aerosols. That's one of the reasons I'm not keen to publish this somewhere like Atmospheric Environment (where both my article and Bjarke's, the bases of this work, were published). I'm really kicking myself now for not submitting an abstract for this as a contributed talk at ISBA. I would've got a BA article out of it. In happier news, I gave a presentation with two other PhD students to BRAG this morning where we talked about INLA. It went well and I think we've convinced a few of the others that INLA is pretty cool and worth using. Edit: and I'm getting a lot of mileage out of the Finnish/finish pun.