---
title: Non-parametrics reading group
author: Sam Clifford
date: 2012-03-01
tags: ["blog","Blog","brag","conferences","nonparametrics","qut"]
---

At the [8th Bayesian Non-parametrics workshop](http://bnpworkshop.org/) in Veracruz, Mexico, last year I met a very enthusiastic grad student from UC Berkeley, [Tamara Broderick](http://www.stat.berkeley.edu/~tab/). I spent a lot of time hanging out with Tamara and a bunch of the other PhD students attending the conference and I got to know about the reading group that she'd set up within the UC Berkeley Statistics Graduate Student Association (of which she is co-president). Tam's reading group, "Classics of NP Bayes", are working their way through a lot of the foundational papers of Bayesian non-parametric statistics, the papers that are always cited but seldom read. Inspired by this and hungry for more knowledge about NP Bayes (my only real experience at the time being semi-parametric regression with splines) I asked around the Bayesian stats group at QUT if anyone was interested in setting up a similar group here. In August 2011 the QUT NP Bayes reading group held its first meeting to decide a structure, meeting frequency, and discuss what kind of papers we wanted to read. Six or seven months later we have made our way through a number of papers, theoretical and applied, and learned quite a lot along the way. This morning I will be giving a presentation to the Bayesian stats group about our progress and writing the slides has really made me realise just how far we've all come together. Our little group consists mostly of PhD students, with backgrounds as varied as applied stats, computational maths, econometrics, environmental statistics, computer science, and we now have an electrical engineer from outside the School of Mathematics joining us to get more of a background in the techniques he's using (Latent Dirichlet Allocation and Hierarchical Dirichlet Processes). We've covered measure theory, the Poisson process (as a completely random measure), the Dirichlet process, infinite mixture models and density estimation, the Polya urn formulation of the DP, MCMC methods for DP models, the Gaussian process and its relationship with GMRFs, non-parametric covariance regression and will spend our next few meetings on the Chinese Restaurant and Indian Buffet processes. I'm really glad with the way things have turned out, and if you're interested in reading more about the topics we've covered you can check out the [NP Bayes review slides](http://samcliffordinfo.files.wordpress.com/2012/03/npbayes.pdf) or our [wiki](https://wiki.qut.edu.au/display/npbayes/Home).