---
title: Posterior samples
author: Sam Clifford
date: 2012-11-09
tags: ["andrew gelman","bayesian statistics","blog","Blog","courses","ecology","elections","posterior samples","R","statistics","visualisation"]
---

*   [<span style="line-height:12px;">Content from very popular online R course run through Coursera to be published online soon</span>](http://simplystatistics.org/post/34563838584/computing-for-data-analysis-simply-statistics-edition)
*   [Convinced your fancy analysis technique is the right approach? Run it on noise and see what you get](http://www.statisticsblog.com/2012/10/recommendation-of-the-week/)
*   [Science news from science newsmakers](http://scienceseeker.org/)
*   [Should ecologists become Bayesians?](http://statisfaction.wordpress.com/2012/11/06/just-for-the-fun-of-it/)
*   If you've got a colour graph but want to print it black and white, make sure you check what it looks like first. [Otherwise you might struggle to make your point.](http://i.imgur.com/krzQu.jpg)
*   [Andrew Gelman on poll aggregation and election forecasting](http://andrewgelman.com/2012/11/poll-aggregation-and-election-forecasting/)
*   [Nate Silver's book is #2 on the Amazon best-seller list at the moment](http://www.amazon.com/The-Signal-Noise-Predictions-Fail-but/dp/159420411X/ref=zg_bs_books_2)
*   [Speaking of Nate Silver, here's a blog post on the politicisation of statistical literacy. (Bonus round: Ctrl-F "Schwimmer". Extra bonus round: Andrew Gelman comments, saying "I wrote about this on my blog", just like everyone else on the internet)](http://simplystatistics.org/post/34635539704/on-weather-forecasts-nate-silver-and-the)