---
title: Gelman and Robert
author: Sam Clifford
date: 2012-05-25
tags: ["andrew gelman","arxiv","blog","Blog","christian robert","journals","papers","qut","science","seminar"]
---

Kerrie Mengersen, one of my supervisors, is visiting some colleagues in France at the moment. It appears that one of the outputs of this visit is a discussion paper, "In praise of the referee", written with Nicolas Chopin, Andrew Gelman and Christian Robert ([arXiv](http://arxiv.org/abs/1205.4304)). There's been a lot of discussion recently about the role of journals, publishers and reviewers in academic publishing ranging from defending the _status quo_ to totally overhauling the system by shedding paper journals and moving everything online to a distributed network of institutional ePrints repositories. The paper by Chopin et al. makes two recommendations after a lengthy discussion about where we find ourselves

1.  Post-publication peer review with comment threads on arXiv and/or a filtering service where instead of acting as reviewers, editorial boards pick out worthwhile new research as a list of recommended reading.
2.  A reviewer commons where academics are taught how to review and the reviewer reports (and their names) are published alongside the article.

The article is worth a read. I figured I'd also share an old Gelman blog post that he's recently linked to, "[Advice on writing research articles](http://andrewgelman.com/2009/07/advice_on_writi/)". The seven pieces of general advice are well worth remembering. It's basically "Start with your conclusions and work backwards towards your methods". Christian Robert has [published the dates for his Australian tour](http://xianblog.wordpress.com/2012/05/25/xian-australian-tour-2012/). I'm not particularly interested in ABC but the talk on Rao-Blackwellisation looks interesting. Anyone who's interested in learning a bit about what Bayesian simulation is, without necessarily having a statistics background, would do well to attend the public talk entitled "Simulation as a universal tool for statistics", which you could probably consider as a popular science talk.