---
title: The Wald is not enough
author: Sam Clifford
date: 2012-06-25
tags: ["aerosols","blog","Blog","conferences","ilaqh","isba","qut","science","statistics"]
---

I'm working on a talk I'm presenting at Healthy Buildings 2012 while I do some travel to ISBA. My supervisor, who is president of the Healthy Buildings conference this year, saw [a blog post of mine](http://samclifford.info/2012/06/01/statistics-not-just-for-statisticians/) and thought that it would make a good presentation for the student plenary session. The basic point of the talk is that the quality of scientific research is greatly improved by ensuring that appropriate statistical analysis is performed and presented clearly. There have been so many papers and presentations I've seen where the authors just stop at descriptive statistics of their data and draw inferences just from describing the data. If we're lucky they'll do a t-test or ANOVA. If we're not, they'll just calculate summary statistics and perhaps a correlation between the response and the covariates rather than doing any statistical modelling. The problem isn't restricted to indoor air quality and climate, the focus of this conference, though. [A friend of mine](http://conidialcoleopticide.wordpress.com/) has come across the same issue in her literature review for using microbes to control insect pests. There are some groups doing some amazing scientific work with robust statistics, such as Hugh Possingham's group at UQ who look at applying econometric principles to conservation (think triage for species rather than patients). At the risk of spoiling the ending of my talk, being "the statistician" in my group has given me the opportunity to work on some interesting aerosol science problems such as particle loss in instrumentation, the multi-modality of SMPS data and how it affects automatic processing, microbiology populations in classrooms, the fate of non-background ions and determining exposure measures from personal samplers and monitoring equipment that have different time steps. In turn, I have introduced the researchers I'm working with to new statistical techniques (often with R code) which they can adapt and use in future work. Every group needs a statistician in it, but not just to be handed the data to analyse and used as a black box where data goes in and analysis comes out. For starters, the statistician needs to know what the data actually describe. But the statistician should be there to build the skill set of the group. We can't expect that every scientist has PhD level statistical skills but the scientist needs to be comfortable going beyond ANOVA to investigate what's happening in their experimental or observational data. P.S. the title for this talk was inspired by a brief conversation with my ISBA room-mate about how great statistics-based puns are.