---
title: Christian Robert coming to Australia
author: Sam Clifford
date: 2012-03-20
tags: ["asc","blog","Blog","christian robert","conferences","isba","qut","seminar","statistics"]
---

One statistician whose blog I follow, Christian Robert (silent _t_), is [coming to Australia](http://xianblog.wordpress.com/2012/03/20/amsi-lecturer/) later in the year. Far from being just a blogging statistician, Robert is Professor of Statistics at the University of Paris Dauphine and does a lot of [interesting research](http://www.ceremade.dauphine.fr/~xian/research.html) in a variety of fields related to statistical modelling, statistical theory and computation. Some of Robert's most recent work includes Approximate Bayesian Computation, on which some of Tony Pettitt's students and post-docs at QUT (where Robert is an Adjunct Professor, and I wonder how long he'll stick around here) are working. Robert will be speaking at the Australian Statistics Conference and then doing a [speaking tour](http://www.amsi.org.au/research-a-higher-education/rhenews/828-prof-christian-robert-lecture-tour) for the Australian Mathematical Sciences Institute. I'll be going along when he's in Brisbane but will miss him at ASC2012\. Robert will be speaking on the Monday prior to the main ISBA 2012 conference and will cover advances and questions in ABC, so I still might get the chance to see him and talk to him before his speaking tour.