---
title: Git used to write high school maths textbook
author: Sam Clifford
date: 2012-10-02
tags: ["blog","Blog","creative commons","education","finland","git","mathematics"]
---

As a mathematician who uses git and LaTeX to collaboratively write papers with Finnish researchers, the following story is really neat. [A group of Finnish mathematicians, students and teachers got together and hacked out a draft upper secondary school level mathematics textbook](http://linja-aho.blogspot.fi/2012/09/a-group-of-finnish-math-teachers-write.html). There's still some tidying up to be done but a snapshot's available [here](http://cloud.github.com/downloads/linjaaho/oppikirjamaraton-maa1/version-0.9.pdf). [The collaborators used git](https://github.com/linjaaho/oppikirjamaraton-maa1/) to weave together the various parts of the book, allowing them to work on separate sections of the book and feed them back to github. One of the benefits of something like git is that when two people work on the same section and both try to commit their changes it flags the conflict and forces you to resolve it. Using Google Docs to collaborate like this leads to people getting in each others' way and overwriting each other. Using Dropbox results in a forked version of the conflicted file with no sensible way to resolve the conflict. If you read the comments in their blog post you'll see stories of other researchers doing similar work to create books. That the Finns are releasing their book under a CC-BY license means that others can take their work, [fork the git repository](https://github.com/linjaaho/oppikirjamaraton-maa1/network) and derive and compile their own versions of the book. If you speak Finnish, [their Facebook page](https://www.facebook.com/oppikirjamaraton) might also be of interest.