---
title: Posterior samples
author: Sam Clifford
date: 2012-11-14
tags: ["blog","Blog","brian eno","cellular automata","eclipse","music","posterior samples","R","solar eclipse","xkcd"]
---

*   [Randall Munroe explains Saturn V using only the thousand most commonly used English words, and it's hilarious](http://xkcd.com/1133/)
*   [Speaking of Randall Munroe, here's his response to Gelman's criticism of Munroe's Bayesian vs Frequentist comic](http://andrewgelman.com/2012/11/16808/#comment-109366)
*   [Some (but not my) thoughts on teaching R to 50,000 students](http://simplystatistics.org/post/35563800852/some-thoughts-on-teaching-r-to-50-000-students)
*   [There was an eclipse visible in Australia on the morning of November 14 2012](http://www.abc.net.au/local/stories/2012/11/13/3631638.htm)
*   [It's getting hammered at the moment, but The Infinite Jukebox analyses songs for similar phrases and builds a series of paths between similar sections so that you can have an infinitely long song.](http://musicmachinery.com/2012/11/12/the-infinite-jukebox/)
*   The Infinite Jukebox reminds me a bit about [Brian Eno's work on generative systems](http://www.youtube.com/watch?v=UqzVSvqXJYg) for rule-based music. This in turn reminds me of Brian Eno's album "Discreet Music", which features an [automatically played song and three re-arrangements of Pachelbel's "Canon in D". ](http://www.youtube.com/watch?v=7-Vq4pmzMaE) The album is designed to sit in the background and be fairly unobtrusive, but it's hard not to notice the familiar phrases of "Canon in D". I find this album good as background music at work. The generative systems video above takes me back to my undergraduate studies in mathematics, where we learned about [mathematical modelling using cellular automata](http://staff.qut.edu.au/staff/malletd/).