---
title: Posterior samples
author: Sam Clifford
date: 2012-12-11
tags: ["ada lovelace","blog","Blog","eclipse","graphs","mathematics","R","science communication","solar eclipse","video","visualisation"]
---

*   <span style="line-height:12px;">[Nice infographic of Mars missions](http://www.statisticsblog.com/2012/12/information-graphics/) showing all attempts and planned attempts</span>
*   As much as I love using .csv files to send data back and forth, especially on GitHub, apparently I should [stop using Excel-like files to exchange data](http://www.win-vector.com/blog/2012/12/pleases-stop-using-excel-like-formats-to-exchange-data/)
*   There are some really lovely visualisations of quite profound and complex scientific ideas among [The best scientific figures of 2012](http://www.wired.com/wiredscience/2012/12/science-figures-2012/)
*   As someone who espouses the beauty of LaTeX and [the importance of proper font choice](http://samclifford.info/2012/08/12/credibility-of-information-given-font-choice/), [The Anatomy of Type](http://typeanatomy.com/) is a book I'm considering buying. Maybe I should get it for my sister for Christmas.
*   [A charming comic with an origin story for Ada Lovelace](http://sydneypadua.com/2dgoggles/lovelace-the-origin-2/).

And, yes, I do plan on writing more about what I'm actually doing! I'm just working on thesis stuff a lot and trying to organise my final seminar. I've got some thoughts on presentations that I'm writing up, so stay tuned. One more [*   Stunning time lapse photography of the eclipse.](http://exp.lore.com/post/37688902608/60-seconds-of-awe-in-this-timelapse-of-the)