---
title: ISBA 2012
author: Sam Clifford
date: 2012-02-29
tags: ["blog","Blog","conferences","isba"]
---

I've just submitted a poster abstract and travel support grant application for the [ISBA 2012](http://www2.e.u-tokyo.ac.jp/~isba2012/) World Meeting, "Bayesian spatio-temporal modelling of ultrafine particle number concentration from a panel design" and is a nice overview of the modelling involved in the UPTECH project that we're running at ILAQH. It's based on the second paper that will comprise my PhD (still in prep but coming along well) and discusses quantifying temporal trends at multiple sites. I've had a few breakthroughs with the code recently and wish that I had've had them towards the end of last year so I could submit an abstract for a paper. The travel support grant for ISBA required an extended abstract and I think it'd make a good presented paper but contributed session proposals closed a _long_ time ago. I'd love to go to [ASC 2012](http://www.sapmea.asn.au/conventions/asc2012/index.html) and present this stuff there but [Healthy Buildings](http://hb2012.org/) is on the same week (and I'm on the Student Program Committee).