---
title: Open access and my next paper
author: Sam Clifford
date: 2012-04-19
tags: ["arxiv","blog","Blog","elsevier","ilaqh","inla","open access","publishing","qut","science","statistics"]
---

I got some substantial feedback from one of my supervisors earlier in the week and I've been chopping and changing this paper to ensure that the results section is more than just "Look at these graphs. They are graphs." and that the introduction actually introduces the problem before leaping into how we propose to solve it. Another one of my supervisors will always pick me up on my use of informal language. I tend to write as if I'm explaining how I went about solving a problem, which is very well suited to tutorials, blogging and the [NP Bayes Wiki](https://wiki.qut.edu.au/display/npbayes/home) (the reading group is currently on hiatus) but less well suited to academic papers which will be sent to peer reviewed journals. I need to keep working on my formal scientific writing. Part of that probably means reading more academic papers from start to finish rather than skimming them for the information that I need. It probably also doesn't help that most of the methodological stuff that I'm writing is drawn from the documentation and FAQs of an R package as well as personal communication with the authors of said package (said package is [R-INLA](www.r-inla.org)). I've got three papers on the go at the moment, so it's going to be important that I can pick the low-hanging fruit of avoiding informal language so that my supervisors can concentrate on the actual work when giving me feedback. I've recently been spending a fair amount of time thinking about, and discussing with some colleagues, the issues of the [Elsevier boycott](http://thecostofknowledge.com/), open access publishing and the use of preprint repositories like [arXiv](http://arxiv.org/). QUT supports open access to some extent by running an [ePrints](http://eprints.qut.edu.au/) repository, where university researchers are encouraged to deposit a preprint of their work (not the version published by the journal), and [subscribing to, or taking out membership with](http://libguides.library.qut.edu.au/content.php?pid=84068&sid=624559), a few open access journals. Some of these are quite highly regarded, particularly publications by the Public Library of Science, such as [PLoS ONE](http://www.plosone.org/home.action). The bulk of our papers at ILAQH end up in Elsevier's [Atmospheric Environment](http://www.journals.elsevier.com/atmospheric-environment/), quite a respectable journal, but I feel uncomfortable propping up a business with such a coercive business model that allows them to operate at a [profit level of 36](http://www.nytimes.com/2012/02/14/science/researchers-boycott-elsevier-journal-publisher.html?_r=1)%. Sure, Adam Smith tells us that the baker is a baker not out of a love of bread but out of a desire to earn money with which to live, but we don't have to accept the terms of business of one large company. I'm particularly interested in journals where the authors retain the copyright (or in the case of QUT, [the authors' institution](http://www.mopp.qut.edu.au/D/D_03_01.jsp#D_03_01.05.mdoc)). I'm also a fan of journals which are innovating in the modern publishing environment, such as the [American Statistical Association](http://www.amstat.org)'s [Journal of Statistical Software](http://www.jstatsoft.org/) which is not only open access but publishes each article as its own issue of the journal, increasing the frequency of publication to a point where when an article's reviewed it's published straight away. I don't like Elsevier's business model and would be happy to look at publishing in high quality open access journals where the authors don't have to sign away their copyright to the publishers. After all, it's not the journals funding or doing the work. I believe granting the publishers a time-limited exclusive license to publish would be a far better model. There are other journals with a similar level of credibility and respect that don't require authors to sign over copyright, don't coerce libraries into taking big packages with unwanted journals bundled in and don't freeze the person in the street out of reading the results of publicly funded research (a lot of research in Australia is funded by the [Australian Research Council](http://www.arc.gov.au/), a government funding body). I don't think Elsevier are evil, but they have a terrible business model in terms of disseminating high quality research to the public in an affordable manner. There are others out there doing a better job and researchers should support them.