---
title: Where do I want to go?
author: Sam Clifford
date: 2012-11-01
tags: ["aerosols","bayesian statistics","blog","Blog","jobs","science","statistics"]
---

As my PhD draws to a close, I'm beginning to spend some time thinking about where I want to go to work after QUT. I applied for, have been offered and now accepted, a 0.5 full time equivalent position for one year with the NHMRC Centre for Air quality and health Research and evaluation (CAR) which will start when I submit my PhD. ILAQH will contribute the remaining 0.5 FTE so that I've got full time employment, jointly between CAR and QUT, and I'll be based in Brisbane. The next year is going to be a flurry of paper writing, collaboration and reviewing the work the group does. I've been talking about moving overseas for work for quite some time. I've been at QUT since I started undergrad in 2002 and while I've done a few subjects here and there at other universities (computational physics at UQ, some climatology at USQ) and taught maths at [Krome Studios](http://www.kromestudios.com/) for about a year (one or two sessions a week) I've been at QUT almost constantly. This wouldn't necessarily be a permanent move overseas, I am open to coming back to Australia (after all, it's where my family is) after a few years of postdoctoral work overseas. The list below is a few places I've been considering and have previously checked their websites for postdoc work. I would like to continue working on Bayesian statistical applications but also perhaps continue to go further into methodology and work a bit more on the computational statistics side of things as I feel my undergrad/honours skills are getting a bit rusty.

*   [University of Helsinki - Bayesian Statistics Group](http://www.helsinki.fi/bsg/)
*   [Aalto University - Bayesian Statistical Methods](http://becs.aalto.fi/en/research/bayes/)
*   [University of Minnesota - Biostatistics](http://www.sph.umn.edu/biostatistics/ourfaculty/bayesian/)
*   [Ohio State University - Statistics](http://www.stat.osu.edu/)
*   [Duke University - Statistical Science](http://www.isds.duke.edu/)
*   [Colorado State University (Boulder) - Statistics](http://www.stat.colostate.edu/)
*   [Statistical and Applied Mathematical Sciences Institute](http://www.samsi.info/)
*   [National Center for Atmospheric Research](http://ncar.ucar.edu/)

I'm undecided as to whether I should apply to work at Berkeley, Stanford, MIT, Harvard, or any other big name places. Sure, they're prestigious but I got some advice from a friend a few months ago that what you want in a job is

*   good people to work with
*   a project that interests you
*   a project that's interesting to others (which means they can hire you next)

and don't want to end up slogging my way through six to twelve months of interesting work with someone at a big name institution that I don't really want to work with.