---
title: Biopesticide research programs at QUT
author: Sam Clifford
date: 2012-09-21
tags: ["bayesian statistics","blog","Blog","chemistry","genetics","invertebrate pests","jobs","mathematics","mathematics project","microbiology","pesticides","phd programs","queensland university of technology","qut","research","research scholarships","science","statistics"]
---

The email below the cut details three PhD programs that are based on the level above me in the Biopesticides lab at QUT. All projects involve collaboration with researchers in the UK; the mathematics project involves collaborating with [researchers at Oxford](http://www.maths.ox.ac.uk/contact/details/whites) and the other two with researchers at [CABI](http://www.cabi.org).

*   [Chemistry](https://fileshare.qut.edu.au/public/hauxwell/Higher_Degrees_Research_Projects_Proposal_Form___chemistry.pdf) - The interaction between insect cuticular chemistry and pathology and gene expression in Metarhizium anisopliae
*   [Mathematics](https://fileshare.qut.edu.au/public/hauxwell/Higher_Degrees_Research_Projects_Proposal_Form___maths.pdf) - Development of mathematical models of insect pathogen dynamics
*   [Genetics](https://fileshare.qut.edu.au/public/hauxwell/Higher_Degrees_Research_Projects_Proposal_Form___roots.pdf) - Colonisation of the rhizosphere by entomopathogenic fungi: gene expression, metabolite translocation and impacts on invertebrate pests

If you're interested in these, contact [Associate Professor Caroline Hauxwell](http://staff.qut.edu.au/staff/hauxwell/).

> Dear all I'm looking for applicants for 3 PhD students in the current round. Please would you pass this on to anyone you think might be interested? Applications to QUT's research scholarships **close Oct 12 2012.** Interested applicants should first send a CV and expression of interest stating how your skills and experience will help you to address the research questions to A/Prof Hauxwell **by 5th October at the latest**. Details of QUT's scholarships and full application requirements (due 12th October) can be found here:
> 
> *   [http://www.qut.edu.au/research/scholarships-and-funding/research-scholarships](http://www.qut.edu.au/research/scholarships-and-funding/research-scholarships)
> 
> Outlines of the three projects can be found here:
> 
> *   [https://fileshare.qut.edu.au/public/hauxwell/Higher_Degrees_Research_Projects_Proposal_Form___chemistry.pdf](https://fileshare.qut.edu.au/public/hauxwell/Higher_Degrees_Research_Projects_Proposal_Form___chemistry.pdf)
> *   [https://fileshare.qut.edu.au/public/hauxwell/Higher_Degrees_Research_Projects_Proposal_Form___maths.pdf](https://fileshare.qut.edu.au/public/hauxwell/Higher_Degrees_Research_Projects_Proposal_Form___maths.pdf)
> *   [https://fileshare.qut.edu.au/public/hauxwell/Higher_Degrees_Research_Projects_Proposal_Form___roots.pdf](https://fileshare.qut.edu.au/public/hauxwell/Higher_Degrees_Research_Projects_Proposal_Form___roots.pdf)
> 
> Thanks carrie Dr Caroline Hauxwell Associate Professor Queensland University of Technology