---
title: ANOVA
author: Sam Clifford
date: 2012-10-19
tags: ["anova","bayesian statistics","blog","Blog","ilaqh","nonparametrics","qut","science","statistics","uptech"]
---

ANOVA is one of those things that all the scientists in my group do when writing a paper where there's more than one group, which is totally natural and a good first step for data analysis. Whether it's looking at the mean concentration of some aerosol at the UPTECH schools, the level of diesel engine emissions by fuel type or some other experimental setup, ANOVA will typically make it into a paper (even if only as a _t_ test). ANOVA (or a _t_ test) may not always be an appropriate test to use, e.g. if the data is not normal, has a few large outliers or exhibits some sort of reliance on a covariate. In such cases it may be better to use a regression model with a non-Gaussian likelihood. This week I've spent a bit of time getting to grips with the Mann-Whitney U test as a way of testing medians, another summary which is used for aerosol concentrations. It's not featured in Excel, so the person I was helping had to dust off their SPSS skills and we eventually made our way through and figured out how to run the test. But descriptive statistics of quantiles or measures of central tendency aren't nearly as exciting as something I've come across, functional ANOVA. I met Cari Kaufman at ISBA earlier this year and we had a bit of a chat about spatio-temporal models of climate data with Gaussian processes and Gaussian Markov Random Fields. When I got back to Brisbane I decided to have a look at what she's written and whether I should think about applying to work with her at Berkeley. Kaufman has [a 2010 paper](http://ba.stat.cmu.edu/journal/2010/vol05/issue01/kaufman.pdf) [1], which appears to have its genesis [at least as far back as 2007](http://andrewgelman.com/2007/10/anova/), where functional ANOVA is discussed as a way of testing whether some observed effect (which may be a nonlinear function) is the same across groups. The examples given include temperature records in Canada and spatio-temporal modelling of regional climate in the UK. I would like to go over the functional ANOVA paper with the QUT NP Bayes reading group, as it's a very interesting use of the Gaussian process prior. I'd also like to use it in my own work, as the question "Is the daily trend the same at each school?" is of interest to me. [1]  Cari G. Kaufman and Stephan R. Sain, "Bayesian Functional ANOVA Modeling Using Gaussian Process Prior Distributions", _Bayesian Analysis_ 5, 2010, pages 123-150\. [[PDF](http://ba.stat.cmu.edu/journal/2010/vol05/issue01/kaufman.pdf)]