---
title: Posterior samples - July wrap
author: Sam Clifford
date: 2013-07-29
tags: ["aerosols","andrew gelman","bayesian statistics","blog","Blog","christian robert","education","ilaqh","posterior samples","publishing","questacon","qut","science","seb113","statistics","video","visualisation"]
---

I had some Posterior Samples to share before going on leave but didn't get around to posting them. Here's what's been on my mind this month: Maths and science units are popular with (Kentucky) students until they realise that [they're hard](http://blogs.wsj.com/economics/2013/07/08/math-science-popular-until-students-realize-theyre-hard/). While not directly relevant to the Australian university education model it's probably an important thing for the Science and Engineering Faculty to keep in mind. [](http://blogs.wsj.com/economics/2013/07/08/math-science-popular-until-students-realize-theyre-hard/) I'm looking at ggplot2 more these days, so the idea of a "grammar of graphics" is beginning to resonate with me. [Here's a talk](//www.youtube.com/watch?v=xyGggdg31mc) about building one for [clojure](http://clojure.org/) (which I don't use). Something for me to keep in mind when delivering SEB113 slides this semester is [what your maths slides don't need](https://www.dropbox.com/s/p0sgdgo7mxkoj4h/What%20your%20math%20slides%20dont%20need.pdf). Probably also good pointers for any PhD students graduating soon. [An interesting article in the New York Times](http://well.blogs.nytimes.com/2013/07/22/the-kitchen-as-a-pollution-hazard/) about air pollution from cooking. This is something that ILAQH has a research interest in and our nanotracer paper contains a bit of analysis of inhaled surface area dose from particles that originate from cooking. [Another NYT article](http://www.nytimes.com/2013/07/22/business/in-climbing-income-ladder-location-matters.html), this time with a delicious visualisation of the geographical trends in income disparity and social mobility. [Andrew Gelman writes at Slate](http://www.slate.com/articles/health_and_science/science/2013/07/statistics_and_psychology_multiple_comparisons_give_spurious_results.html) about some of the problems with scientific publishing and the publication of spurious findings (which isn't always willingly dishonest). A special "Big Bayes Stories" issue of "Statistical Science" will be published soon, focussing on the real world application of Bayesian statistics where other methods were inapplicable. [Christian Robert has written the preface](http://xianblog.wordpress.com/2013/07/29/big-bayes-stories/); the issue is being edited by Robert, Kerrie Mengersen (one of my PhD supervisors) and Sharon McGrayne, author of "[The Theory That Would Not Die](http://www.amazon.com/Theory-That-Would-Not-Die/dp/1452636850)". Also I went to [Questacon](http://www.questacon.edu.au/) and it was awesome.