---
title: Use of credible intervals in scientific papers
author: Sam Clifford
date: 2013-11-04
tags: ["bayesian statistics","blog","Blog","journals","papers","science","statistics"]
---

I just got comments back from reviewers for two papers that our group has submitted. I've done the statistics on both papers and given that Bayesian statistical models have been used in both papers (and we've been pretty up front about it) we've used credible intervals to discuss the uncertainty in our parameter estimates. A comment I've received from a few reviewers (and indeed co-authors) is something along the lines of

> please replace all instances of 'credible interval' with 'confidence interval'.

While I don't expect every scientist to be intimately familiar with Bayesian statistics, its philosophy and the fundamental differences between confidence and credible intervals, the repeated use of a term would tend to indicate that it's not a one-off typo. If repeatedly confronted in a paper with a term that one is not familiar with, surely the prudent course of action is to do a quick Google search to see what that term means in order to better understand the paper that one is reviewing. While the war within statistics over whether the Bayesian approach is actually statistically valid is over, awareness of it in the sciences seems to be lagging far behind. Air quality journals do publish papers that have a Bayesian flavour to the statistics and I have a feeling that just about every author that submits a paper with the correct way of summarising parameter uncertainty in a Bayesian model will face the same comment, "please replace all instances of 'credible interval' with 'confidence interval'".