---
title: Becoming a grown up (at least a grown-up academic)
author: Sam Clifford
date: 2013-08-30
tags: ["blog","Blog","conferences","education","ilaqh","papers","qut","science","seb113","statistics","uptech"]
---

There are only four months left in my current postdoctoral appointment and I'm discussing plans for next year with my supervisor. There's still a lot of unfinished UPTECH work that needs to happen, including helping a handful of PhD students with the stats in their papers for their thesis, dealing with the clinical data and putting together some research plans for what to do next. The plan at the moment is to look for some funding both internally and externally to provide a research appointment. I'm also interested in continuing lecturing next year, whether in SEB113 or another mathematics/statistics unit. Most of ILAQH is away as of today or tomorrow, as they travel to Prague for the [2013 European Aerosol Conference](http://eac2013.cz/). The work that I've been doing with some colleagues from ILAQH and Italy, on personal sampling, will be featured on a poster. The paper has been submitted to ES&T but hasn't been accepted yet, so unfortunately I can't put a preprint up to show off the cool statistics that I had to learn to do the modelling in the paper. As a result of everyone being away, I'll be one of two academic staff members left here. It's going to be quiet, with most of the staff and a few PhD students gone. Barring the Finnish paper that I'm still revising, this personal sampling paper has been the paper which has required the most creative and original programming as there have been many different steps along the way. I am particularly proud of this paper and the work that went into it. When I was first brought on board there didn't appear to be much clarity regarding what we wanted to investigate; we had a lot of personal sampling data but didn't quite know what to do with it. I think the paper we've developed does service to the amount of work that was put into collecting the data and is aligned with what the UPTECH project was set up to do. I'm grateful to all co-authors on the paper (and everyone who was out there in the schools) for the work that they put into bringing this to fruition. I'm still finishing the final corrections for my thesis, due in a few weeks time. After that's handed in I'll be taking another step in becoming a grown-up academic: supervising a PhD student. I'll be the replacement associate supervisor for a student whose original associate supervisor has moved from QUT to another university. QUT requires an internal primary and associate supervisor and I'm the one most familiar with the modelling that this student is doing as part of their thesis. We've already set a meeting schedule for the time when his primary supervisor is overseas and have discussed what sort of things I'll expect to see. It's a strange responsibility to have for someone who's only just finishing up their thesis. I wonder how long it will be until I'm the primary supervisor for a student. Two years? Five? Ten? Worrying about funding, writing grant applications, supervising students, lecturing (writing assessment!). It's a strange place to find oneself.