---
title: An argument for why careful coding in R is better than an Excel spreadsheet
author: Sam Clifford
date: 2013-04-18
tags: ["andrew gelman","blog","Blog","economics","excel","programming","R","statistics"]
---

I spend a fair amount of energy encouraging my coworkers to use R because you can write reusable code that means checking for errors is simple and you can re-run it on different data sets without having to manually copy and paste all your data and fix up any indexing if it's the wrong length. There's been a bit of buzz recently about how two economists really dropped the ball when they published a paper showing that high levels of national debt as a percentage of GDP slows economic growth. I won't write any more about it because it's been done by better writers and statisticians, but I'd like to bring your attention to the following articles:

*   <span style="line-height:12px;">[The original working paper](http://www.nber.org/papers/w15639.pdf) (National Bureau of Economic Research)</span>
*   [Replicating the results](http://www.peri.umass.edu/236/hash/31e2ff374b6377b2ddec04deaa6388b1/publication/566/) (Political Economy Research Institute) [was only possible by making huge methodological and data selection mistakes](http://www.nextnewdeal.net/rortybomb/researchers-finally-replicated-reinhart-rogoff-and-there-are-serious-problems) (Next New Deal)
*   [This may have led to massive avoidable unemployment around the world](http://www.guardian.co.uk/commentisfree/2013/apr/16/unemployment-reinhart-rogoff-arithmetic-cause) (The Guardian)
*   [The authors should gracefully retract, admit they were wrong and move on](http://andrewgelman.com/2013/04/16/memo-to-reinhart-and-rogoff-i-think-its-best-to-admit-your-errors-and-go-on-from-there/) (Andrew Gelman's blog)
*   [And to use R](http://andrewgelman.com/2013/04/17/data-problems-coding-errors-what-can-be-done/?utm_source=feedly) (Phil at Gelman's blog) [rather than Excel](http://andrewgelman.com/2013/04/17/excel-bashing/?utm_source=feedly) (Andrew Gelman)
*   There are many reasons to not use Excel, such as it providing the wrong answer for [paired t-tests](http://people.stern.nyu.edu/jsimonof/classes/1305/pdf/excelreg.pdf) and [being terrible at generating Normal random numbers](http://or.nps.edu/faculty/PaulSanchez/oa4333/handouts/Excel/excel2000.pdf).