---
title: Some good news
author: Sam Clifford
date: 2013-11-29
tags: ["blog","Blog","conferences","emac2013","grants","papers","phd supervision","qut","science","statistics"]
---

[Our personal sampling paper got accepted for publication](http://pubs.acs.org/doi/abs/10.1021/es403721w) <span style="line-height:1.714285714;font-size:1rem;">quite quickly once we'd made the changes the reviewers required. This paper came from almost nothing about a year and a half ago to a really nice piece of mathematical and statistical modelling that will give us a lot to work with in future UPTECH papers, where we'll be looking at the relationship between inhaled dose and child health. I'm presenting this work at the EMAC2013 conference next week (gotta write slides!) so it's good to have the paper online now.</span> My current post-doc is drawing to a close at the end of the year but I've got the contract in the email for my position for the next few years. After that, who knows? We got a grant under an international exchange program which means I may be off overseas for a few weeks/months during my next appointment. I'm looking forward to being able to spend some time outside the country at another university, having got a bit more experience now than when I went to Finland about two years in to my PhD. And it looks like I'm about to get my second PhD student to co-supervise.