---
title: Ex Post Docto
author: Sam Clifford
date: 2013-07-08
tags: ["blog","Blog","ilaqh","phd","qut","research","science","statistics","uptech"]
---

I am now at the half-way point in my year-long postdoctoral fellowship. Since the start of the year the number of papers submitted with my name on them has approximately doubled, I've got my name on some grant applications (some successful, some not) and am co-writing a proposal for a PhD student position at ILAQH that I will likely end up co-supervising. It's been quite the experience so far and it's really only just getting started. I've been applying for lecturing positions at QUT and will continue to look further afield to see what's out there that inspires me. Today the staff and post-docs in my group had a meeting to discuss the handling of lab business and how we maintain our space. For the longest time I've felt like a bit of an outsider, particularly with regards to lab stuff. I couldn't tell you how to maintain a CPC, what the difference between a P-trak and Q-trak is or how to compare SMPS to NSAM data. I was not a member of the measurement team for UPTECH and my involvement in the research is mainly through data analysis and statistical consultation. Being given responsibilities within the lab is still a bit strange to me but I'm very happy to be helping out, as I am part of a team and I rely on those around me for my work. Statistics doesn't happen in a vacuum (unless you're a probabilist). A friend of a friend is finishing up their chemistry PhD and looking for work for next semester and beyond. They're applying for a more technical job and we spent some time this evening with our mutual friend (who has recently started a postdoc) discussing how to rearrange the CV in order to best highlight their experience. I showed [my own CV](http://samclifford.info/?attachment_id=291) to explain what I wanted to highlight, as all three of us had different opinions on style, format, the flow of the text and whether to include a photograph or not. Obviously I'm pitching myself at academic, rather than technical, positions and I said that I believe professional experience in a lab is far more important to show off than academic awards from undergrad. An interesting moment in the conversation was the disbelief from the friend of a friend that I would make my CV so public. Why wouldn't I want to show the world who I am, what I'm working on and what I'm interested in? It appears that developing multiple versions of a CV is necessary in order to have something to send to different bodies. University faculties are looking for a very different set of attributes than the Australian Research Council or other funding groups. I haven't yet managed to whittle my CV down to two pages but I suspect it would include removing much of the tutoring and undergraduate experience I've had, my radio and TV interviews and conference organisation background, focussing instead on my top publications, professional experience and track record with grants. I will continue to need to tweak my CV as I continue to apply for jobs and this means having a look around for good resources from those who have gone before me. Some examples of advice I've come across are:

*   [Boost your postdoc chances (at The Research Whisperer)](http://theresearchwhisperer.wordpress.com/2013/05/14/postdoc-chances/)
*   [What if your CV is not enough? (at The Thesis Whisperer)](http://thesiswhisperer.com/2011/05/26/what-if-your-cv-is-not-enough-part-one/)
*   [The transit from PhD student to post-doc (at Trockeneisbombe)](http://trockeneisbombe.wordpress.com/2013/07/04/the-transit-from-phd-student-to-post-doc/)

All of those blogs are worth following anyway. The next six months will be a challenge, as I attempt to juggle the remaining time in this postdoc with other commitments and the need to find ongoing employment.