---
title: There is so much I don't know that I wish I did
author: Sam Clifford
date: 2013-05-09
tags: ["bayesian statistics","blog","Blog","brag","ilaqh","programming","qut","science","statistics"]
---

There are things I've heard of and never followed up like Expectation Maximisation (and Variational Bayes, for that matter), Expectation Propagation and Hamiltonian Monte Carlo. Things I once learned about and forgot because I didn't have the background at the time such as Importance Sampling, Rejection Sampling, Slice Sampling. Then there's things that are the cutting edge of statistical research that aren't necessarily statistical methods but means of implementing them and are transforming the way we do statistics, such as CUDA. I've managed to pick up a few little statistical novelties along the way such as nonparametric Bayes, hierarchical linear models and some of the theory behind GMRFs and Gaussian Processes but I feel like I'm lagging behind where I want to be. This could be a consequence of being based in a group with no other statisticians. Were I doing my postdoc in a statistics group I'd be more deeply immersed in a group with a culture of doing statistics research rather than doing scientific research which requires statistics I already know.