---
title: Posterior samples
author: Sam Clifford
date: 2013-08-22
tags: ["blog","Blog","brian eno","jeff leek","joe hanson","mathematics","music","posterior samples","programming","R","sas","science","statistics"]
---

Life can be tough when you're the [only statistician in your group](http://simplystatistics.org/2013/08/09/embarrassing-typos-reveal-the-dangers-of-the-lonely-data-analyst/). In addition to attempting to communicate statistical ideas with scientists who may only understand statistics as far as linear regression and ANOVA, the communication runs both ways and everyone needs to be clear on what's being done, how it's being done, and how you write that up. Check all papers for comments before they're submitted, otherwise you may end up leaving yourself open to falsifying your data. SAS still dominates job advertisements for statisticians ([or data scientists](http://simplystatistics.org/2013/08/08/data-scientist-is-just-a-sexed-up-word-for-statistician/) if there is indeed a distinction) but [R jobs are on the rise](http://blog.revolutionanalytics.com/2013/08/job-trends-for-statistics-packages.html). It'd be interesting to see if this is related to the cost of licensing and training for SAS. I was checking out [a website](http://3.14-pi.net/) that was posted on [Joe Hanson's Tumblr](http://www.itsokaytobesmart.com/) when my supervisor walked in and asked what I was looking at. The site lists off the digits of π and plays a kick drum sounds for 0, a hi hat for 1, and tones on a scale for 2 to 9\. "What purpose does this have?" I don't know, but it's a neat little thing and there's no repeating melody thanks to the irrationality of π. This reminds me a little of Brian Eno's "[Generative Music](http://en.wikipedia.org/wiki/Brian_Eno#Generative_music)", which uses some initial sounds to generate unique melodies, through adjustable parameters, that may not repeat for long, long, long periods of time (of the order of thousands of years, potentially). Eno released [an entire album](http://www.youtube.com/watch?v=KE86wbZhlWYwhich) of such music but I much prefer "[Ambient 1: Music for Airports](http://www.youtube.com/watch?v=RfKcu_ze-60)" which uses tape loops of varying lengths and phasing to create musical patterns whose lengths are [incommensurable](http://en.wikipedia.org/wiki/Commensurability_(mathematics)).