---
title: EMAC2013 semi-wrap
author: Sam Clifford
date: 2013-12-04
tags: ["Blog","conferences","emac2013","mathematics","qut","science","statistics","uptech"]
---

Today's the final day of EMAC2013, starting with Joe Monaghan's talk on numerical methods for the dynamics of fluids that contain particles (in 20 minutes, so I'll be brief). I attended yesterday's "Education" session and saw some interesting things about how maths education is going around the country. The University of Tasmania is engaging with TasTAFE to deliver maths courses to engineering diploma students in order to prepare them for the mathematics they'll encounter in their bachelor's degrees. UTS is doing some interesting analysis of their maths course results to rejig the prerequisite pathways for their maths courses. A particularly interesting case was the use of a first year linear algebra course as a predictor of performance in a second year stochastic models subject that previously only had a first year probability course as its prerequisite. I chaired and presented in yesterday's "Environment" session, presenting the mathematics behind the [personal sampling](http://pubs.acs.org/doi/abs/10.1021/es403721w) that we've been working on with the UPTECH project. I got quite a number of good questions and was overall quite happy with the talk I gave. The other talks in the session were about: using approximations to a sum of Pareto distributions, developed by actuaries, to determine whether extreme values in biomass luminescence were real or artifacts from the new sensors; and incorporating insolation into global climate models. Josef Barnes (Griffith) won the student prize (for, I assume, his talk on cardiac geometries), with honorable mentions for Kristen Harley and Lisa Mayo (QUT) and Laith Hermez. Bill Blyth, for whom the prize is named, pointed out the quality of the student talks at EMAC2013 is getting higher year after year. This can only be good news for the applied mathematics sector in Australia (and New Zealand) as these students will likely go on to academic positions and generate high quality research. David Lovell gave a great talk yesterday about multi-, inter-, trans- and ante-disciplinary research. I'm reading [the article](http://www.ploscompbiol.org/article/info:doi/10.1371/journal.pcbi.0010006) he referred to yesterday about the way disciplines will have to deal with each other and knowledge sharing over the coming years. And I'm off.