---
title: Posterior Samples
author: Sam Clifford
date: 2013-12-02
tags: ["bayesian statistics","blog","Blog","conferences","emac2013","inla","mathematical modelling","mathematics","posterior samples","programming","R","robotics","statistics","visualisation"]
---

Thiago Martins has posted [a neat little tutorial](http://tgmstat.wordpress.com/2013/11/28/computing-and-visualizing-pca-in-r/) about using R to calculate and visualise Principle Components Analysis, using Fisher's Iris data. PCA is something I've struggled with as I've gone further into statistics, as it comes across as being based on mathematics rather than statistics. I'd like to learn more about the Indian Buffet Process and associated non-parametric Bayesian methods but if I'm going to be looking at long and wide data sets (say, UPTECH questionnaire data) I'd like to have somewhere to start. It looks like this may provide that. Rasmus Bååth's done [a tutorial on Laplace Approximations in R](http://www.sumsar.net/blog/2013/11/easy-laplace-approximation/) (hat tip to Matt Moores for this one). Laplace Approximations are an alternative to MCMC simulation that can provide good approximations to well-behaved posterior densities in a fraction of the time. The tutorial deals with the issue of reparameterisation for when you've got parameters which have bounded values (such as binomial proportions). As a piece of trivia, Thiago (above) is based at NTNU where [R-INLA](http://www.r-inla.org/) is developed. I'm at the [emac2013](http://emac2013.com.au/) conference this week. We're about half way through day one of the talks (of three) and there's already been some fascinating stuff. Professor Robert Mahony (ANU) gave a talk that shows that the development of more advanced unmanned aerial vehicles (UAVs, drones) involves some quite complex but elegant mathematics, involving Lie group symmetries, rather than just coming up with cooler robots. Hasitha Nayanajith Polwaththe Gallage (QUT) showed some really interesting particle method (mesh-free) modelling where forces and energies were used to determine the shape of a red blood cell that had just ejected its nucleus.