---
title: Posterior Samples
author: Sam Clifford
date: 2013-01-21
tags: ["blog","Blog","books","journals","open access","publishing","statistics","visualisation"]
---

[Free download](http://blog.revolutionanalytics.com/2013/01/elements-of-statistical-learning-2nd-ed-download.html) of Hastie, Tibshirani and Friedman's "Elements of Statistical Learning". Hastie and Tibshirani did a lot of the early work on Generalised Additive Models and non-parametric smoothing, albeit in a non-Bayesian framework, so this will no doubt be an invaluable resource. NASA have released [a neat visualisation](http://www.nasa.gov/topics/earth/features/2012-temps.html) of spatio-temporal deviation from the mean temperature going back to the 1880s. You have to be careful when generating "pretty" graphics, though, because ["pretty" infographics can be quite ugly and hard to decode](http://andrewgelman.com/2013/01/ugly-ugly-ugly/) when you're not taking into account what the data actually represents. [Roger Peng](http://www.biostat.jhsph.edu/~rpeng/) [reviews](http://simplystatistics.org/2013/01/16/review-of-r-graphics-cookbook-by-winston-chang/) Winston Chang's "R Graphics Cookbook". The conclusion? A pretty good collection of examples about how to complete particular graphing tasks using ggplot2\. It's a simpler book than Hadley Wickham's "ggplot2" and would be a good introduction to using ggplot2 to achieve a particular goal. [JSTOR's "Register & Read"](http://about.jstor.org/rr) is in beta now. So if you're not attached to a university or other institution with a JSTOR subscription, you now have the opportunity to read JSTOR articles for free (but it's not unlimited, at least not yet). Speaking of free access to published research, [this opinion article](http://www.guardian.co.uk/science/blog/2013/jan/17/open-access-publishing-science-paywall-immoral) makes the point that our job as scientists is to contribute to the body of human knowledge for the benefit of society and so if a paper isn't freely available to the public then it isn't really "published". Not only that, but to hide research behind a paywall is immoral. I found it very interesting even if I thought some of his arguments were a bit dismissive.