---
title: Meta-analysis? Meta-regression?
author: Sam Clifford
date: 2013-05-14
tags: ["bayesian statistics","Blog","ilaqh","microbiology","papers","programming","qut","R","science","statistics","uptech"]
---

Meta-analysis with a covariate feels really weird. I'm wanting to compare the relationship between the distributions of the mean concentration of endotoxin in the air and in dust samples across 50 locations. I wasn't sure I did it the right way but the posterior estimates are consistent with my naïve approach of regressing the means of the air and dust samples. It's important to account for the variability when doing this sort of _post hoc_ analysis because a point estimate of the mean doesn't reflect anywhere near the full set of knowledge you have about your parameters of interest. On an unrelated note, another UPTECH paper has been [published](http://pubs.acs.org/doi/abs/10.1021/es400041r). This one's looking at spatial variation of particle number concentration in the school environment. Congratulations to Farhad Salimi, the first author of this paper, on the publication of his first paper. Farhad's one of the PhD students on the UPTECH project and is due to finish his thesis later this year. I've worked with him on two of his papers (this one and another which has been submitted) and he's really thrown himself into learning how to use R. This has not only made it easier for me to collaborate with him but it's also made his analysis possible.