---
title: Posterior samples
author: Sam Clifford
date: 2013-06-13
tags: ["bayesian statistics","blog","Blog","christian robert","conferences","derp","guy marks","kerrie mengersen","programming","publishing","R","social media","statistics","sydney","woolcock"]
---

[Josh Tucker at the Monkey Cage](http://themonkeycage.org/2013/05/29/how-to-make-an-academic-conference-and-more-accessible-and-more-interesting-live-streaming-and-conference-hashtags) and [Jeff Leek at Simply Statistics](http://simplystatistics.org/2013/06/11/why-not-have-a-future-of-the-field-session-at-a-conference-with-only-young-speakers/) have some good ideas and goals as to how to make academic conferences more interesting. Opening up the conference with live streaming is a cheap way to engage the wider public (but risks potential attendees deciding to stay home and watch rather than engaging with the rest of the conference). A youth session is also a really good way to engage in some inter-generational communication by giving the younger researchers a stage for setting out their vision. [These journals](http://f1000research.com/data-policies) wouldn't view publication of data as prior publication when assessing an article based on that data. I spent last week in Sydney with Guy Marks' group at the [Woolcock Institute of Medical Research](http://www.woolcock.org.au/). I first met Marks at Bayesian data analysis course run by Kerrie Mengersen; he [does work](http://sydney.edu.au/medicine/people/academics/profiles/guym.php) on tuberculosis in Vietnam. Christian Robert, a collaborator of Mengersen's, just gave 40 students in Ho Chi Minh City a crash course in Bayesian statistics. The slides are available [here](http://xianblog.wordpress.com/2013/06/05/teaching-bayesian-statistics-in-hochimin-city/). Speaking of Bayesian stats, the term "derp" is apparently a [Bayesian way of describing the way someone believes something so strongly](http://au.businessinsider.com/sorry-haters-derp-isnt-going-away-2013-6) (their prior) that they can not be swayed by data. I'm going to be doing a lot more work teaching people how to use R in the near future. [This looks like a handy resource for beginners](http://www.computerworld.com/s/article/9239625/Beginner_s_guide_to_R_Introduction).