---
title: Posterior samples
author: Sam Clifford
date: 2013-10-16
tags: ["ada lovelace","blog","Blog","economics","nobel prize","posterior samples","spatial statistics","statistics","wikipedia","women in science"]
---

Christian Robert gives [a brief review](https://xianblog.wordpress.com/2013/10/14/statistics-for-spatio-temporal-data-book-review/) of the latest version of Noel Cressie's book on spatial statistics. I met Cressie once a few years ago and have found the 1993 edition of his book really useful in my PhD. I may just have to get my hands on this new version. Sometimes in your analysis there'll be an overall trend which is apparent but when you look at subgroups of the data all of them have a trend going the opposite way. This is called Simpson's paradox and is explained with an interactive tool [here](http://vudlab.com/simpsons/). A [primer](http://simplystatistics.org/2013/10/14/why-did-lars-peter-hansen-win-the-nobel-prize-generalized-method-of-moments-explained/) about why Lars Peter Hansen won the Nobel Prize for Economics. This is probably as close as we can get to a Nobel Prize for Statistics (do the Fields Medal and Abel Prize count?). [Lip Mag interview](http://lipmag.com/featured/where-have-all-the-wiki-ladies-gone/) with Kelly Wong about women in science. Wong's a Brisbane-based PhD student whose supervisor has worked with my supervisor, so I guess we're like research cousins once removed. The interview raises questions about the recognition of women in science on Wikipedia. This is all related to [Ada Lovelace Day](http://www.theguardian.com/technology/2013/oct/15/nerd-cabaret-wikipedia-ada-lovelace-day-2013?CMP=twt_fd) (Lovelace was the first computer programmer), which will feature wikipedia edit-a-thons to ensure that our big online repository of human knowledge and history reflects the achievements of women in STEM.