---
title: Understanding uncertainty
author: Sam Clifford
date: 2013-10-29
tags: ["bayesian statistics","blog","Blog","posterior samples","ronald fisher","statistics","video"]
---

Ah, the [Monty Hall problem](http://en.wikipedia.org/wiki/Monty_Hall_problem). AKA "What? HOW!? Is this magic?" [Here's a nice little Flash site](http://www.stayorswitch.com/) that simulates the Monty Hall problem and asks you whether you're going to switch or stay and shows the stats of the number of people who've switched and stayed and how often they've won the car. The great thing about the Monty Hall problem is that it's a great example of the use of Bayes' theorem and Game theory. [This is a fun video](http://www.youtube.com/watch?feature=player_detailpage&v=bVMVGHkt2cg) starring Ronald Fisher explaining how to test the effect of some treatment (flicking the top of beer cans affecting whether or not it sprays everywhere) using hypothesis tests. It goes into quite a bit of the nuance of hypothesis testing. I especially like that Fisher discusses how p values for a hypothesis test are uniformly distributed.