---
title: Maturing from student to researcher
author: Sam Clifford
date: 2013-06-17
tags: ["andrew gelman","bayesian statistics","blog","Blog","qut","research","statistics","sydney"]
---

[The other week, when I was in Sydney](http://samclifford.info/2013/06/06/trips-interstate/ "Trips interstate"), I caught up a friend who's moved down there and is working in a similar role to me (albeit with a much larger group). He's got a similar background to me; we both studied mathematics at QUT and focussed on computational and applied mathematics units but we now find ourselves working in (bio-)statistics*. I stayed in academia when he went off to work in industry but he has earned a Masters in computational statistics and has picked up Bayesian stats. We both learned Bayesian stats through Gelman, Carlin, Stern and Rubin's "[Bayesian Data Analysis](http://www.stat.columbia.edu/~gelman/book/)", a book which is known to the Bayesian PhD students at QUT as "The Bible"; it's been used by just about every lecturer that has taught the Honours level Bayesian Data Analysis class. In addition to The Bible, other Bayesian resources I've leaned on over the last few years are [Gelman and Hill's book on hierarchical models](http://www.stat.columbia.edu/~gelman/arm/) and [Gelman's blog](http://andrewgelman.com/). My friend and I got talking about Gelman's work and how of late we seem to be disagreeing with some of the choices he makes in modelling. For my part, I don't agree with (or is it understand?) the decisions in Gelman's Bayesian approach to [ANOVA](http://www.stat.columbia.edu/~gelman/research/published/econanova3.pdf) (focussing more on the variance parameters than the means) and the particular parameterisation of the [global variance parameter](http://projecteuclid.org/DPubS/Repository/1.0/Disseminate?view=body&id=pdf_1&handle=euclid.ba/1340371048) when he discusses the use of a folded non-central _t_ distribution. Now, it's not that I think Gelman is wrong where he was previously right or that he's losing the plot (after all, these papers are years old), but as I read his blog about the models he's fitting now I'm coming to the realisation that I had been following what he'd been saying and am now looking elsewhere and seeing other ways of doing things. There are many different approaches that each have their strengths and weaknesses and philosophical (and practical) idiosyncrasies. One of the strengths of the Bayesian approach is that the incorporation of priors in the modelling approach gives you a very flexible class of models (hierarchical Bayesian modelling is one of the most useful tools I've picked up) and allows you a great amount of freedom in choosing how to build your priors. There is no one correct prior for each problem<sup>ยง</sup>; you can use a Jeffreys' prior if you really want to go down the path of non-informativity or if you're content with (and can justify) a weakly informative Normal(0, 1e-6) or Gamma(0.001, 0.001). Sometimes you can even choose an appropriately flat prior that results in the posteriors of your parameters having the same distribution as the frequentist approach (where the 95% confidence interval and credible intervals have the same values, but not the same interpretations of course). Sometimes it's appropriate to elicit a prior from experts or the literature and go for a very informative prior if you don't have much data in your experiment/observation^. There are lots of different ways to do things, lots of papers pushing different approaches. As a student you tend to look up to people as paragons of the field and go "Well if Gelman did it that way then I'd better do that too"; after four years of study I feel more comfortable looking at something and saying "No, I disagree". I may not always be doing it the best way possible but I'll always try to justify what I've done both to my collaborators and to the editor/reader of my papers. If it turns out I've done something wrong, so be it; I can always try again and learn from the experience. * I'm yet to hear a satisfactory explanation as to what the difference is between a biostatistician and a statistician. ยง It's worth checking out some of the ideas of so-called [Objective Bayes](http://ba.stat.cmu.edu/journal/2006/vol01/issue03/berger.pdf) if subjectivity is something you're concerned about. ^ Whatever you do, check your sensitivity to your choice of priors.