---
title: Posterior samples
author: Sam Clifford
date: 2013-04-29
tags: ["andrew gelman","bayesian statistics","blog","Blog","comic","posterior samples","public health","science","statistics","xkcd"]
---

Often we don't [discuss the various technical tricks](http://dynamicecology.wordpress.com/2013/03/18/whats-your-best-technical-trick/) that make the science easier in the methodology sections of our papers. Randall Munroe made [a chart](http://xkcd.com/1205/) that helps you figure out whether you're spending more time working on your time-saving technical trick than you'd actually save. SAMSI [hosted a talk](http://samsiatrtp.wordpress.com/2013/04/25/samsi-hosts-simons-foundation-public-lecture-the-public-health-impact-of-air-pollution-and-climate-change/) about the public health impact of climate change. Wish I could have been there. A few (somewhat) recent posts from Andrew Gelman regarding p values

*   <span style="line-height:12px;">[reporting probabilities instead of p values](http://andrewgelman.com/2013/04/28/plain-old-everyday-bayesianism/) is very Bayesian</span>
*   [p values and statistical practice](http://andrewgelman.com/2013/02/p-values-and-statistical-practice/)

I find myself agreeing with a lot of what Gelman says on p values. I think they put the focus of statistics on testing rather than modelling, which is part of why we end up with scientists and others with such poor statistical skills and next to no creativity in terms of the models they fit.