---
title: Talks
author: Sam Clifford
date: 2013-10-11
tags: ["blog","Blog","communication","ilaqh","phd","qut","science","seminar"]
---

I'm not sure if I've discussed this before but there's a huge difference in culture between the two research groups I'm involved with. ILAQH (physics) meets once every four to six months at the moment and BRAG (statistics) meets fortnightly. At the fortnightly meetings we spend a few minutes having a quick check-in around the room where we discuss what we've been up to for the last two weeks (any papers published, talks given, new research plans) and then someone will give a talk on a topic that is within a semester-long theme. The theme last semester was visualisation, now we're moving on to the analysis of big data. ILAQH, by contrast, meets at a frequency that doesn't really facilitate a catch-up. Instead, any big developments in the big projects are discussed and visitors are welcomed and/or farewelled appropriately. Both meetings serve different purposes in different ways. One of the biggest benefits of the BRAG fortnightly meetings is that PhD students get a lot of practice giving talks. You're almost expected to give a talk once a semester, and students are encouraged to give practice talks for the milestones of their PhD candidature (confirmation at 12 months, final seminar when completed). Given that it's typically two and a half years between confirmation and the final seminar, being expected to give a talk every few months means that you get practice at talking and that the practice is somewhat regular. This will be especially important for ILAQH students as an overwhelming majority of our students are not native English speakers. Getting regular practice at academic speaking will help when it comes to final seminars. I've spoken to Lidia Morawska (Director of ILAQH) about setting up such a system and she thinks it's a good idea. Now I've just got to check that the rest of the group sees it as valuable and then put the legwork in to get it off the ground (organise a time, book a room, etc.).