---
title: Generating mastery through immersion, imitation and failure
author: Sam Clifford
date: 2013-01-03
tags: ["blog","Blog","comic","journals","publishing","science","statistics"]
---

I came across a webcomic, Doodle Alley, which deals with sustainable creativity and there are a few pages I want to focus on: "[Taste is your teacher](http://doodlealley.com/2012/10/01/taste-is-your-teacher/)", "[Be friends with failure](http://doodlealley.com/2012/10/10/be-friends-with-failure/)" and "[Practice does not make perfect](http://doodlealley.com/2012/11/21/practice-does-not-make-perfect/)". They are couched in terms of art, but I think the same arguments apply to academic science as well, particularly writing papers. "Taste" focuses on immersion as a means of improving your work. To adapt the culinary example to statistics: to write a good paper I need to know what good statistics looks like; to know what good statistics looks like I need to read a lot of good statistics. This reminds me of the [JRSS B](http://onlinelibrary.wiley.com/journal/10.1111/(ISSN)1467-9868) papers I've had to read to understand spatial statistics [1, 2]. "Taste" mentions imitation as a way of producing great art and this is explored further in "Practice". This doesn't mean word for word plagiarising in the academic arena, but I'd say it does mean that copying the original creator's style and extending it is part of the road to success. In writing my thesis I looked at previous PhD students' theses which were held up as being great work. I looked at the way the thesis was structured, the way the ideas were set out within each chapter and the way the conclusion stepped through what the work had resulted in. I obviously couldn't just "copy" the thesis, because their work is not my work and I need to make a significant original contribution, but the thesis as a whole can definitely serve as a starting point for my imitation of good art. "Friends" starts with the very sobering realisation that the more you immerse yourself in great art (science) the more you realise your art (science) is not great. The solution to this is to embrace failure as a friend and recognise that [sucking at something is the first step towards being sorta good at something](http://www.youtube.com/watch?v=vrBWJLC22mE). The comic raises the point that if you never fail at something how can you grow? One of the first things you learn in impro is that failure is an indication that you have tried. If, as beginners, we never fail we are playing it safe and producing boring work. Only by taking those bold leaps and falling flat on our faces multiple times do we begin to feel comfortable with our failure. Platitudes about failure being a learning experience don't tend to focus on the idea that failure is something to be embraced but that it's something that just happens and there's nothing we can do about it. Failure, in the comic, is evidence that you're still like a baby in terms of picking up a particular skill. Babies are born knowing absolutely nothing and pick it up by repeating their attempts, failing a little less each time they try. This is the key to mastery. Immerse yourself in your field, get a sense of what great art/science/statistics/food is and keep on trying, taking those bold steps and failing a little less each time. Your first few academic papers will probably not be worth publishing in journals like JRSS B and JASA, but that's no reason to not aim high, fail (get rejected), try again (revise) and get the best result for what you've produced (a less prestigious journal but it's still published work). Mastery is built through a combination of immersing yourself in others' great work, imitating that great work, taking bold steps, recognising that you will fail, embracing the idea that you will fail and that you will fail less each time you try not through repetition of the exact same act but by trying different things until you get something that's "good enough". Then by repeatedly failing and trying new things you will learn where the pitfalls are and you will fail less and, every so often, create something that is great. [1] Lindgren, F., H. Rue and J. Lindström, (2011) "An explicit link between Gaussian ﬁelds and Gaussian Markov random ﬁelds: The SPDE approach", JRSS B ([pdf](http://www.math.ntnu.no/inla/r-inla.org/papers/spde-jrssb-revised.pdf)) [2] Banerjee, S., A. Gelfand, A. Finley and H. Sang, (2008) "Gaussian predictive process models for large spatial data sets", JRSS B ([pdf](http://www.biostat.umn.edu/~sudiptob/ResearchPapers/BGFS.pdf))