---
title: Posterior samples
author: Sam Clifford
date: 2013-01-10
tags: ["blog","Blog","education","journals","open access","publishing","science","statistics","twitter"]
---

[A very comprehensive paper by Vehtari and Ojanen discusses various aspects of model assessment and comparison](http://andrewgelman.com/2013/01/a-important-new-survey-of-bayesian-predictive-methods-for-model-assessment-selection-and-comparison/). I was mentioning to a friend the other day that I don't think model assessment is taught very well in first year statistics classes. I recognise that you can't teach everything in a first year class, but I think we should be going beyond R<sup>2</sup> as a summary of model performance. Even the AIC would be a good start, as it incorporates a trade-off between goodness of fit and model complexity. I am yet to fully read the paper but it's something I should definitely get my head around. [Dynamic Ecology has some advice for how to review a journal article](http://dynamicecology.wordpress.com/2013/01/03/advice-how-to-review-a-manuscript-for-a-journal/). This will become increasingly relevant for me as a junior researcher. No doubt I'll be asked whether I could review some submitted articles for a journal in which I am publishing my papers. Having not done it before, the first one will no doubt be the toughest. Perhaps I should ask the more junior reviewer of my thesis panel for any recent experience they've had. [JSTOR's "Register & Read"](http://www.insidehighered.com/news/2013/01/09/jstor-offer-limited-free-access-content-1200-journals) program is an attempt to open up access to academic publishing by allowing individuals not affiliated with an organisation with a JSTOR subscription to read three articles every two weeks for free. This will be good for when news articles discuss a study and people are interested enough to go and find the original paper but don't want to drop $30 to read it. It's not as far-reaching as Open Access but it's a good step. [#OverlyHonestMethods](https://twitter.com/search/%23overlyhonestmethods) is a hilarious Twitter hashtag that is encouraging scientists to confess their transgressions and is [being called](http://io9.com/5974256/overlyhonestmethods-is-the-postsecret-of-the-science-world-and-it-is-amazing) the [PostSecret](http://www.postsecret.com/) of the science world.