---
title: New papers on the way
author: Sam Clifford
date: 2013-08-17
tags: ["aerosols","blog","Blog","chemistry","microbiology","papers","qut","science","statistics","uptech"]
---

In addition to the Endotoxin paper which was accepted after revisions earlier this week, we are very close to submitting papers on the following topics:

*   trends in and ratios of indoor and outdoor PNC in the UPTECH schools
*   24 hour personal sampling and dose metrics for children in the UPTECH schools
*   modern Bayesian spatial statistical techniques
*   particle losses by size in diffusion dryers and thermodenuders

In addition to these, a few papers are nearing completion but are not yet ready for submission. These include

*   fungus concentrations in the UPTECH schools
*   flame retardants in dust in the UPTECH schools
*   particle emission and deposition rates for indoor sources in the UPTECH schools

So, yes, my plate has been rather full recently with all the various research activities in which I've been enlisted. These are all fascinating examples of the interaction of statistics and science and have all required different approaches to quantify what's going on. Some of these have been fairly obvious modifications to things I've already done and some have required me to look quite deeply into new approaches and figure out both what the model is and how we go about implementing it. I am particularly happy with coming to terms with the combination of a Poisson regression model for total counts and a multinomial for proportions within that count, particularly when some of the classes in the multinomial may have zero counts. That model was a challenge but and I think the paper that it gets used in is much stronger than similar papers which have just taken a very naive approach to analysing the data. One of the biggest challenges with this particular paper has been communicating with the scientists I'm working with. These people are definitely not Bayesian statisticians and don't come from a medical science background, which tends to be more accepting of complex models that replace ANOVA. I've had to write a few paragraphs for the flame retardants in dust paper that describe the model we're using. Hopefully that helps make the analysis more accessible to the co-authors but also those reading the paper who haven't got postgraduate qualifications in statistics.