---
title: How do you keep track of your group's papers?
author: Sam Clifford
date: 2013-01-11
tags: ["blog","Blog","databases","ilaqh","qut"]
---

UPTECH is probably the biggest and most collaborative project my research group has ever embarked upon. Bringing together aerosol researchers at ILAQH, clinical medical scientists at the Woolcock Institute for Medical Research and international collaborators, it is likely to generate about fifty papers in the coming years. We currently have no system for keeping track of who is working on what and how developed each paper is. It's probably too big for one or two investigators to keep in their head and I don't think a Word document or Excel spreadsheet is going to cut it. I spent some time this afternoon mucking around in Microsoft Access in an attempt to figure out how I could put a relational database together that's built well enough to capture information about authorship, where the authors come from, which journal or conference the paper is being submitted to, etc. but still be simple enough that the people in my group, who are not database experts (and I'm certainly not one), can manage to operate it fairly painlessly such that they'll actually use it. I had a play with the "Projects" template but it was a bit too much, even though it did have some nice features such as the ability to import contact details from Outlook. I ended up making a table for papers and a table for people and set up a form for data entry. The "people" table feeds a drop down selection for lead author and a drop down multiple selection field for co-authors, which was quite simple to set up and is going to make things much easier. It works for the time being and I've got a few things I'd like to add, such as queries to return which papers a person is working on, how many lead author papers each person has, etc. it's going to be a much more interesting way to learn about Access and databases than maintaining the utterly massive UPTECH database that was designed by someone else and then passed to me. Although if there are purpose built systems for this sort of thing I am more than willing to listen to what others use.