---
title: Science as storytelling
author: Sam Clifford
date: 2013-11-06
tags: ["blog","Blog","communication","mathematics","pedagogy","phd","qut","science","science communication","seb113","statistics","teaching"]
---

I used to not be a very confident public speaker. I remember getting up at a community meeting in 2007 and stammering some words out to a group of residents; it was a disaster. Motivated for the desire for some money to augment my Youth Allowance payments I applied to be a tutor with the School of Mathematics (QUT) during my final years of undergrad and found that I became a bit better at talking to people. My Honours seminar was still a nervous affair but it was much less disastrous than the community meeting. After Honours I had a job teaching mathematics to a group of video game programmers, developing the curriculum to suit their needs and interests and it's here that I became far more comfortable with speaking. I was coming up with my own material and delivering it to people who I knew were interested in it. That's a world away from teaching university students, where many may not see the point in learning what I'm teaching. This is especially the case in service mathematics and statistics units. During my PhD studies I got interested in improvised theatre as a creative alternative to the mathematics, statistics and science that was my day. My reputation as someone not afraid to get up in front of 100 people and perform lead to my being asked by one of my PhD supervisors if I'd like to be a tutor in the brand new SEB113 course. Teaching students how to use R for their data analysis? Of course I'm interested! After the end of a very enjoyable, if somewhat disjointed, semester I was asked if I'd consider lecturing the smaller second semester re-run. I jumped at the chance. Restructuring the subject from the way it was run in first semester meant we could focus on the way the material flowed and see if we could smooth out some of the jumps in style, making the unit more consistent and easier to understand. We had to do a lot of work rejigging the slides, writing new workshops and computer laboratory worksheets to accommodate the use of ggplot rather than a combination of base, lattice and MASS graphics. The result was a subject that introduces a diverse list of topics in a much more sensible manner:

1.  Measurement and variation
2.  Visualisation
3.  Summary statistics and confidence intervals
4.  Inference and sample size, hypothesis tests
5.  Regression lines of best fit
6.  Regression with a categorical variable
7.  Non-linear regression based on process models
8.  Multivariate summary statistics and regression
9.  Mathematical modelling of process models
10.  Linear algebra, including the guts of how linear regression works
11.  Writing scientifically, revisiting the scientific method
12.  Writing about numbers, conditional probability for understanding hypothesis tests
13.  Revisiting visualisation
14.  An introduction to advanced quantitative methods

It became apparent around week 8-9 that what we were doing was telling a story of how to get from calculating means to understanding how to develop a model to either model a process or emulate that process. The discussions about writing scientifically became about how the quantitative reports were telling a story. The first step, the introduction, is like meeting the characters for the first time and understanding their relationships with each other. As we move through the methods and analysis we see the action of the story unfold. The conclusion is the consequences of the action and by relating the analysis back to the motivating aim we can see the arc of the story and understand more about these characters. Now that the teaching is over and the marking of the quantitative workbooks is coming to a close, I've got a bit more space in my head to process my thoughts about improvisation and storytelling (we do a weekly show and I'm still doing workshops on the weekend). I've picked up a book on my Kindle by scientist-turned-filmmaker Randy Olson, entitled "[Connection: Hollywood Storytelling meets Critical Thinking](http://www.amazon.com/gp/product/B00FASMHP8/ref=oh_d__o00_details_o00__i00?ie=UTF8&psc=1)". Olson's book is all about how any intellectual topic can be made interesting and accessible by treating its presentation as telling a story. He states that we, as humans, engage with stories far more than we do with dry information as we feel stories it in our hearts, guts and sexual organs rather than just in our brains. Not only is the communication of scientific results storytelling but lecturing is storytelling. I've thought this semester that lecturing is definitely a style of performance, but the idea that the topics in a unit should follow an arc and tell a unified story means that part of the academic's role is telling a story in the classroom. For me, that means that elements of comedy, pantomime and suspense make their way into my lectures. Storytelling in science is a very interesting topic and I look forward to making my way through the remainder of the book over the end of year break, ready to start a new semester with a revised narrative arc and better storyboarding, maybe even a few new characters.