---
title: Just got back from China
author: Sam Clifford
date: 2014-12-09
tags: ["aerosols","Blog","china","ilaqh","science","travel"]
---

I've spent the last few days travelling to and from Beijing, China for the [launch of the new Australia-China Centre for Air Quality Science and Management.](https://www.qut.edu.au/institute-of-health-and-biomedical-innovation/about/news/news?news-id=83099) This is a huge thing for us at ILAQH because it sets up an international collaborative agreement between a bunch of institutions in Australia and China who each have a different set of expertise that they can bring to the table, allowing us to undertake more ambitious projects than before and seek funding from a wider range of sources. There was a lot of prep and behind the scenes meetings to take place on the first day, so Mandana (a colleague of mine) and I took a trip downtown to the Forbidden City and Tian Anmen Square and did some shopping Wangfujin. It would have been cold enough without the wind but it was such a clear day and everything was wonderful. https://flic.kr/p/q1zV8c The first day of the launch, held at [CRAES](http://www.craes.cn/cn/english/welcome.html), featured the constituent groups giving a short presentation about their work. There's a lot of great people working on some really interesting stuff and I'm very excited about the prospect of working with some of them over the coming years. https://flic.kr/p/q26qn7 The second day had us split into three groups to propose various objectives and projects and put names on paper for who might be good leaders or key players in these fields as part of our centre. I joined the Transport Emissions group to discuss the control of emissions at their source, the investigation of atmospheric transformation processes and the development and uptake of new technologies. A lot of the ground work had already been laid at a planning meeting earlier in the year but it was good to put together some more concrete research topics. After this, we went out to the National Jade Hotel for dinner, where we got to try another of the varied styles of Chinese cuisine; this time from a coastal region in North-Eastern China. I wish I had've paid more attention to the names of the various styles, but I enjoyed trying everything over the course of the trip, even the tripe. https://flic.kr/p/pntrDK The final day saw us tidying up the proposals, and an early finish meant that I got the afternoon off with Mandana, Felipe and Dion. After stumbling our way through a menu with pictures but no English translations, we had a big lunch and set off on the subway to the Temple of Heaven. It was certainly warmer than the Forbidden City (less stone, more trees) and was a very peaceful and pleasant end to the trip as we sat down at a bakery café and discussed If You Are The One while eating cream buns and drinking coffee (or in my case, peach black tea with milk). After heading back to the hotel, Mandana and I took a walk around the Bird's Nest stadium which was only a block from our hotel. It looks like Beijing is putting effort into maintaining the area as a public plaza rather than just the grounds of a sports stadium, so even late in the cold evening it was full of families and groups of friends walking, talking and taking photographs. https://flic.kr/p/q3vTaT An early morning taxi to the airport saw the start of 18 hours of travel. It's nice to be back in one's own bed, but I'm off to the airport again tomorrow for a 5:30am flight to Sydney for a workshop on exposure assessment with colleagues from the Centre for Air quality and health Research and evaluation. After a week of disastrously bad coffee, I'm glad that I booked accommodation which advertises itself as being 15m from the Toby's Estate café.