---
title: A few R things
author: Sam Clifford
date: 2014-04-10
tags: ["blog","Blog","mathematics","programming","R","seb113"]
---

"[R: The Good Parts](http://hackerretreat.com/r-good-parts/)" is an attempt to showcase the best way to do things in R. I'm not yet at the stage of dealing with absolutely massive data sets but things will be heading that way for me if aerosol samplers continue to measure at higher frequencies. Left out of the article is a discussion of [dplyr](http://blog.rstudio.org/2014/01/17/introducing-dplyr/); I'm still using functions from the apply family! Maybe I should also get used to using [data.table](http://cran.r-project.org/web/packages/data.table/vignettes/datatable-intro.pdf). (Update: I'm now using data.table and its syntax to apply functions across grouping levels that I've set as keys. This is amazing). While we've been incorporating a few of the mathematical needs of SEB114 into SEB113 it looks like we may need to go a bit further with incorporating the R needs. I hadn't really thought about plotting a specific function (other than a line y = ax + b) in the workshops but it looks like a few earth sciences students need to plot the function π x / (1+x)<sup>2</sup>. So we'll have to take stock over the next six months of what the experimental science lecturers want to put in their units and how we can help support that (also how we can get the science lecturers to help reinforce statistical modelling over statistical testing).