---
title: Paper helicopters
author: Sam Clifford
date: 2014-08-15
tags: ["andrew gelman","blog","Blog","deborah nolan","experimental design","george box","mathematics","pedagogy","qut","science","seb113","seb114","statistics"]
---

There is no textbook for SEB113 - Quantitative Methods in Science. It's not that we haven't bothered to prescribe one, it's that no one seemed to be taking the same approach we decided upon two years ago when the planning for the unit started. There are books on statistics for chemistry, statistics for ecology, statistics for physics, statistics for mathematics, etc. but trying to find a general "statistics for science" book that focuses on modelling rather than testing has been difficult. That said, there are some amazing resources out there if you know where to look, not just for learning statistics but for teaching statistics. One of the most useful that we've come across is "[Teaching Statistics](http://ukcatalogue.oup.com/product/9780198572244.do)", by Andrew Gelman and Deborah Nolan. The book itself is full of advice for things like groupwork, topic order, structure of learning activities, etc. but my favourite thing so far is the paper helicopter experiment. [George Box](http://www.tandfonline.com/doi/pdf/10.1080/08982119208918925) introduced engineering students to statistical design with the paper helicopter. The experiment itself is quite simple and motivates the idea of using statistics to optimise some design by varying the dimensions of the helicopter. As an activity, it's a fun way to collect some data that can be used in analysis. By dividing the class up into groups and getting each group to do one or two different designs it's possible to collect quite a large amount of data, with replication used to identify any group-level effects that may be explaining the variation within the data. There's a great [paper by David Annis](http://www.tandfonline.com/doi/abs/10.1198/000313005X70777#.U-1UePmSx8E) which simplifies the experiment by only varying the length and width of the helicopter's "blade", and explains that fitting polynomials and their interactions may yield a regression surface which explains the variation but ignores the physics of the helicopter. In a class teaching statistics to scientists, any chance to tie the statistics to some scientific context must be leapt upon. One of the biggest challenges in teaching statistics is making it relevant to students so that it doesn't come across as a dry technique for crunching numbers but as a way of probing deeper into a scientific question. I was discussing the experiment with a colleague yesterday who mentioned that when she was learning mathematics at university as part of her science degree it was at the hands of mathematicians who were teaching the unit as if it were for other mathematicians. It was only at the end of the course that a lecturer said "Oh, and by the way, these methods can be used to analyse scientific data". This is the message that needs to come at the start of the class. Statistics (and more generally, mathematics) gives the scientist a set of tools to ask questions of their data. Being able to ask the right question is therefore very valuable. Ignoring the science means you're throwing out all the hard work that went into the experimental design and data collection. This is one reason we focus so much on modelling instead of testing. Stopping your analysis at ANOVA doesn't do justice to your data. Annis' paper shows the derivation of a mathematical model of the motion of the helicopter from force balance equations, terminal velocities and rotational inertia. This mathematical model is then converted to a non-linear regression model. In SEB113 we cover non-linear regression after linear regression and then show where the regression models come from with a week of mathematical modelling. Even though students enrolled in the unit may not have Senior Maths B (assumed knowledge, rather than a formal pre-requisite) many enjoy peeking behind the curtain to see where the models come from. More than that, they are learning that application-specific non-linear models include what is known about the particular application. We explain first order compartment models (pharmacokinetics), asymptotic growth (ecology), the biexponential model (biology) and logistic growth (ecology) models and show the mathematical models that lead to their existence. We've also shown the Lotka-Volterra equations (ecology) in the past as an example of emulating a system, which students seem to enjoy (some are even comforted by the idea that there's no exact solution). This year we'll be adding the paper helicopter model to the mix, performing the experiment in week 5's workshops and analysing the data in the Problem Solving Tasks. I'll try to get some feedback on whether the students enjoy the experiment and can understand and complete the outcomes; I think it's neat, but does it appeal to them? I really like that in the past we've had students who feel ownership of their data by collecting it in SEB114 - Experimental Science and analysing it in SEB113\. SEB114 doesn't run in second semester, though, so we have had to figure out ways of collecting data for analysis and I think the helicopter's the best one we've come up with yet. We've modified the design found in Annis' paper and I've used Adobe InDesign to come up with a printable A4 design where students don't have to do any measuring, just cutting, folding and paper clipping. We have 12 designs available to us, which gives us a lot of flexibility when it comes to parallelising the experiment.