---
title: Posterior samples
author: Sam Clifford
date: 2014-04-26
tags: ["aerosols","andrew gelman","bayesian statistics","blog","Blog","bread","posterior samples","programming","seb113","statistics","video","visualisation"]
---

I'm teaching science students how to do statistics. It would be great if we could turn them into Bayesians, especially seeing as we've just covered the Agresti-Coull correction for estimating proportions from small experiments. [Andrew Gelman has an interesting paper](http://www.stat.columbia.edu/~gelman/research/published/teachingbayes.pdf) on teaching Bayesian statistics to non-statisticians that focuses on the delivery of skills rather than concepts. I would definitely agree with his approach, especially when you consider how he stresses that discussing the model is probably the most important part. NASA have done some work simulating global aerosols and it's been compiled into [a neat video](http://www.itsokaytobesmart.com/post/82630633966/one-of-my-favorite-gifs-of-one-of-my-favorite-nasa) (via [It's Okay To Be Smart's Joe Hanson](http://www.itsokaytobesmart.com/)). CSIRO have been doing some interesting stuff looking at the production of organic aerosols as well, so this is something I'm paying a bit more attention to at the moment. [Datacamp](https://www.datacamp.com/) is a set of online labs for learning to use R, covering the basics of R, data analysis and statistical inference, and computational finance and econometrics. [Learn to be a better coder](https://medium.com/of-games-and-code/d90a50c5d58e) by improving your communication skills. The most practical (in terms of coding, at least) aspect of this includes using meaningful names and writing comments that describe what the code does when it's not clear from the code itself.