---
title: Timetabling and the potential for alternative delivery in SEB113
author: Sam Clifford
date: 2014-04-07
tags: ["blog","Blog","education","pedagogy","qut","science","seb113","statistics"]
---

I've been pretty busy writing the analysis plan for the main paper from the UPTECH project and reorganising SEB113 workshops. We've had some meetings recently with QUT timetabling people which has led to discussions about how we try to get students to enrol in a sensible pair of workshops and labs for both SEB113 and SEB114. One of the biggest concerns when it comes to these paired subjects is making sure that people attend the labs and workshops in the right order and are working with the same groups across both subjects so that we can structure the teaching material. In SEB113 the preferred order of classes is Lectorial, Computer Lab, Collaborative Workshop. The lecture introduces the topic, the lab shows you how it's implemented in R and the workshop gets you working in a group with others to solve a problem based on the topic. The problem comes about with QUT's timetabling software providing a timetable which contains no clashes for the core first year subjects (SEBs 101, 102, 113, 114). Timetabling the lectures/lectorials for these units so that they don't clash is a task in and of itself and I'm impressed that the timetabling people have managed to make sure these subjects don't clash (I remember taking two units for the applied physics co-major in the old B App Sc course where the lectures clashed). The non-clashing timetable doesn't necessarily mean students can enrol in the class order that we would prefer. It's also unlikely that we can automatically combine a lab-workshop pair as one thing to be enrolled in and it's impractical to try to get a staff member to enrol students manually. It's got me thinking a lot about flipped classrooms and other ways of overcoming the timetable difficulty. The benefit of the workshop for students is that they have a group to work with on a big task and they have two tutors to ask for help when they get stuck. I feel like this would be difficult to do outside a classroom without some sort of help-desk queueing system that is only open between certain times (and then you've still got the time restrictions). The computer labs can be done individually at any time, though, as they're about exposure to code rather than solving a particular problem. In this instance, we could probably cut down on the number of computer labs required by encouraging students to do the lab in their own time before their workshop, which is in the spirit of flipped classrooms. The last labs are in week 7 (this week!) which means it's not going to be an issue much longer this semester. Semester 2 has fewer SEB113 enrolments (SEB114 isn't offered) so it's not going to be as big an issue then. Whether we go with changing the timetabling system or we modify computer labs to become programming consults (where to get help you must have attempted the lab) is something we can deal with a bit later. With the use of Echo360 being made mandatory in all lectures at QUT the availability of recorded lectures makes it easier for students to go through the material at their own pace. With so many students in the subject, there's a large number of person hours which go into content delivery. I'm not sure we're using that resource (labour) as effectively as we can, and changing the way we deliver the subject may help that.