---
title: Two pieces of good news this week
author: Sam Clifford
date: 2014-11-05
tags: ["aerosols","bayesian statistics","blog","Blog","collaboration","funding","ilaqh","papers","public health","qut","statistics"]
---

The full paper from the EMAC2013 conference last year is now available online. If you're interested in the statistical methodology we used for estimating the inhaled dose of particles by students in the UPTECH project, you should check out our paper at the [ANZIAM Journal](http://journal.austms.org.au/ojs/index.php/ANZIAMJ/article/view/7819) (click the link that says "PDF" down the bottom under Full Text). More importantly, though, we were successful in applying for an ARC Discovery Project! This project will run for three years and combines spatio-temporal statistical modelling, sensor miniaturisation and mobile phone technologies to allow people to minimise their exposure to air pollution. Our summary of the project, from [the list of successful projects](http://www.arc.gov.au/pdf/DP15/DP15_Listing_by_State_and_Org.pdf):

> This interdisciplinary project aims to develop a personalised air pollution exposure monitoring system, leveraging the ubiquitousness and advancements in mobile phone technology and state of the art miniaturisation of monitoring sensors, data transmission and analysis. Airborne pollution is one of the top contemporary risks faced by humans; however, at present individuals have no way to recognise that they are at risk or need to protect themselves. It is expected that the outcome will empower individuals to control and minimise their own exposures. This is expected to lead to significant national socioeconomic benefits and bring global advancement in acquiring and utilising environmental information.

Other people at ILAQH were also successful in getting a Discovery Project grant looking at new particle formation and cloud formation in the Great Barrier Reef. I won't be involved in that project but it sounds fascinating.