---
title: Posterior samples
author: Sam Clifford
date: 2014-02-13
tags: ["bayesian statistics","Blog","clustering","latex","posterior samples","publishing","statistics"]
---

It's still ARC writing time so that's been taking up quite a bit of time recently. A coworker from Maths mentioned she'd started using [Scrivener](http://literatureandlatte.com/scrivener.php) to storyboard her papers. Apparently [it can be used with tools like git](http://mosx.tumblr.com/post/51299936501/our-collaborative-scrivener-workflows), [Google Drive and Dropbox](http://creativityhacker.ca/2013/04/23/scrivener-and-the-cloud-best-practices-2013/) to work collaboratively but you've got to be careful of conflicted copies that won't be discovered. Another coworker from Maths isn't so impressed by Scrivener, noting that in terms of using it with version control software you're better off using LaTeX anyway. At US$40 a license I'm a bit reluctant to try to make Scrivener part of my workflow, and there's no way I can ask collaborators to fork out that kind of money. I keep being impressed by Matt Wand, Jan Luts and Tamara Broderick's work on [realtime semiparametric regression](http://realtime-semiparametric-regression.net/). I saw Wand present this work at Bayes on the Beach just over a year ago. I can't, for the life of me, wrap my head around mean-field variational Bayes, though. Perhaps it's that I've never had to deal with Calculus of Variations and got into inference beyond linear models through MCMC in WinBUGS rather than through machine learning. I've got a few more books on my desk about statistical theory now, including Congdon's "Bayesian Statistical Modelling", Koller and Friedman's "Probabilistic Graphical Models", Casella and Berger's "Statistical Inference".