---
title: Workshops
author: Sam Clifford
date: 2015-12-14
tags: ["aerosols","bayesian statistics","blog","Blog","ilaqh","qut","science","statistics"]
---

I had a very full week last week, with the annual [Bayes on the Beach](https://botb2015.wordpress.com/) (BOB) at the Gold Coast (Mon-Wed) and [Bayesian Optimal Design of Experiments](https://bode2015.wordpress.com)  (BODE) on Friday. BOB is an annual workshop/retreat, run by Kerrie Mengersen and the BRAG group at QUT, that brings together a bunch of Australian and international statisticians for a few days of workshops, tutorials, presentations and fun in the sun. This year was, I think, my fourth year at BOB. One of the recurring features is the workshop sessions, where around three researchers each pose a problem to the group and everyone decides which one they're going to work on. This year I was asked to present a problem based on the air quality research I do and so my little group worked on the issue of how to build a predictive model of indoor PM<sub>10</sub> based on meteorology, outdoor PM<sub>10</sub> and temporal information. We were fortunate to have [Di Cook](http://dicook.github.io/) in our group, who did a lot of interesting visual analysis of the data (she later presented a tutorial on how to use ggplot and R Markdown). We ended up discussing why tree models may not be such a great idea, the difference in autocorrelation and the usefulness of distributed lag models. It gave me a lot to think about and I hope that everyone found it as valuable as I did. The two other workshop groups worked on ranking the papers of Professor [Richard Boys](http://www.mas.ncl.ac.uk/~nrjb2/) (one of the keynote speakers) and building a Bayesian Network model of PhD completion time. Both groups were better attended than mine, which I put down to the idea that those two were "fun" workshops and mine sounded a lot like work. Still, a diverse range of workshops means something for everyone. [James McGree (QUT)](http://staff.qut.edu.au/staff/mcgreej/) asked me if I could come to the BODE workshop to discuss some open challenges in air quality research with regards to experimental design. I gave a brief overview of regulatory monitoring, the UPTECH project's random spatial selection and then brought in the idea that the introduction of low cost sensors gives us the opportunity to measure in so many places at once but we still need to sort out where we want to measure if we want to characterise human exposure to air pollution. While it was a small group I did get to have a good chat with the attendees about some possible ways forward. It was also good to see [Julian Caley (AIMS)](http://data.aims.gov.au/staffcv/jsf/external/view.xhtml?partyId=900000428) talk about monitoring on the Great Barrier Reef, Professor [Tony Pettitt (QUT)](http://staff.qut.edu.au/staff/pettitt/) talk about sampling for intractable likelihoods and [Tristan Perez (QUT)](http://staff.qut.edu.au/staff/perez5/) discuss the interplay between experimental design and the use of robots. It's been a great end to the year to spend it in the company of statisticians working on all sorts of interesting problems. While I do enjoy my air quality work and R usage is increasing at ILAQH it's an entirely different culture to being around people who spend their time working out whether they're better off with data.table and reshape2 or dplyr and tidyr.