---
title: R Markdown
author: Sam Clifford
date: 2015-12-21
tags: ["Blog","ilaqh","programming","R","seb113","teaching"]
---

I've been spending a bit of time over the last few days making an R tutorial for the members of my air quality research group. Rather than being a very general introduction to the use of R, e.g. file input/output, loops, making objects, I've decided to show a very applied workflow that involves the actual data analysis and explaining ideas as we go along. Part of this philosophy is that I'm not going to write a statistics tutorial, opting instead to point readers to textbooks that deal with first year topics such as regression models and hypothesis tests. It's been a very interesting experience, and it's meant having to deal with challenges along the way such as PDF graphs that take up so much file space for how (un-)important they are to the overall guide and, thinking about how to structure the tutorial so that I can assume zero experience with R but some experience with self-directed learning. The current version can be seen [here](https://samcliffordinfo.files.wordpress.com/2015/12/tutorial-20151221.pdf "tutorial-20151221"). One of the ideas that Sama Low Choy had for SEB113 when she was unit coordinator and lecturer and I was just a tutor, was to write a textbook for the unit because there wasn't anything that really covered our approach. Since seeing computational stats classes in the USA being hosted as repositories on GitHub I think it might be possible to use R Markdown or GitBook to write an R Markdown project that could be compiled either as a textbook with exercises or as a set of slides.