---
title: Marrying differential equations and regression
author: Sam Clifford
date: 2015-01-12
tags: ["bayesian statistics","blog","Blog","differential equations","fabrizio ruggeri","jags","programming","R","seb113","statistics"]
---

Professor Fabrizio Ruggeri (Milan) visited the Institute for Future Environments for a little while in late 2013\. He has been appointed as Adjunct Professor to the Institute and gave a public talk with a brief overview of a few of his research interests. Stochastic modelling of physical systems is something I was exposed to in undergrad when a good friend of mine, Matt Begun ([who it turns out is doing a PhD](http://www.sphcm.med.unsw.edu.au/research/infectious-diseases/phd-candidates) under Professor Guy Marks, with whom ILAQH collaborates), suggested we do a joint Honours project where we each tackled the same problem but from different points of view, me as a mathematical modeller, him as a Bayesian statistician. It didn't eventuate but it had stuck in my mind as an interesting topic. In SEB113 we go through some non-linear regression models and the mathematical models that give rise to them. Regression typically features a fixed equation and variable parameters and the mathematical modelling I've been exposed to features fixed parameters (elicited from lab experiments, previous studies, etc.) and numerical simulation of a differential equation to solve the system (as analytic methods aren't always easy to employ). I found myself thinking "I wonder if there's a way of doing both at once" and then shelved the thought because there was no way I would have the time to go and thoroughly research it. Having spent a bit of time thinking about it, I've had a crack at solving an ODE within a Bayesian regression model (Euler's method in JAGS) for logistic growth and the Lotka-Volterra equations. I've started having some discussions with other mathematicians about how we marry these two ideas and it looks like I'll be able to start redeveloping my mathematical modelling knowledge. This is somewhere I think applied statistics has a huge role to play in applied mathematical modelling. Mathematicians shouldn't be constraining themselves to iterating over a grid of point estimates of parameters, then choosing the one which minimises some L<sup>_p_</sup>-norm (at least not without something like Approximate Bayesian Computation). I mean, why explore regions of the parameter space that are unlikely to yield simulations that match up with the data? If you're going to simulate a bunch of simulations, it should be done with the aim of not just finding the most probable values but characterising uncertainty in the parameters. A grid of values representing a very structured form of non-random prior won't give you that. Finding the maximum with some sort of gradient-based method will give you the most probable values but, again, doesn't characterise uncertainty. Sometimes we don't care about that uncertainty, but when we do we're far better off using statistics and using it properly.