---
title: Blogging about blogging
author: Sam Clifford
date: 2015-12-16
tags: ["blog","Blog","qut","R","research","rstudio"]
---

I was inspired to make a website and start blogging about my work when I went to 8BNP in 2011 and met people like [Kevin Canini](http://canini.me/) and [Tamara Broderick](http://www.tamarabroderick.com/) who had websites to spruik themselves as researchers. I eventually got around to re-setting up my Wordpress account, buying a domain and setting up the whole DNS shebang. The last four years have seen some major changes in the web resources for research, with things like github taking the place of subversion and encouraging a more social and outward facing coding culture. You can blog using github now, and [Nick Tierney](http://www.njtierney.com/jekyll/2015/11/11/how-i-built-my-site/) (a PhD student at QUT) has made me think about whether it's worth migrating from Wordpress to jekyll. Further exposure to R Markdown through Di Cook's workshop at Bayes on the Beach has strengthened my belief in RStudio not just as a way to do research but to communicate it. This is even before we start considering all the things like shiny and embedded web stuff. It'll take some work and I'm not sure I'll have time over summer, but it's a change that's probably worth making.