---
title: A new year
author: Sam Clifford
date: 2017-02-28
---

It's been about a year, and a lot's happened since then. The Diagnostic Quiz has gone from a tool for helping me understand my students better to a tool to help students choose the right pathway through their Science degrees. Now, if a student does poorly on certain sections of the diagnostic, particularly calculus and algebra, we recommend they hold off until SEB113 until second semester and take MZB101 - Introductory Modelling with Calculus - in its place. While I've not had a look yet at all the enrolment data, anecdotally a number of students have contacted me about switching out and have appreciated getting the feedback that they will need to cover a bit more mathematics so that they can understand what they need for their degree. Unfortunately, when a student unenrols from my unit I lose all of their assessment items, which means I don't have a record of the results for the students who move into MZB101\. Perhaps something other than Blackboard (MZB125 - Introductory Engineering Mathematics - use WebWork for their diagnostic) which doesn't link storage to enrolment as tightly would be a useful way to approach this. I'd love to do some analysis at the end of the year of the end of semester marks for those students who transferred out compared to the marks of those who remained in SEB113 but with low scores on the diagnostic. With a cohort with better general mathematics skills than before, we'll be able to spend less time catching up on simple algebra and calculus and more time extending what is covered in high school. I've found some nice physics examples for linear algebra (circuits) and differential equations (Torricelli's law) and will be trying to grab a few more examples that we haven't used before, particularly for assessment. There's a little more movement in our tutorials and workshops towards using packages from the tidyverse for our data munging and analysis. When we started four years ago we were using base graphics, reshape and then reshape2, tapply(), and writing loops with par(mfrow=c(2,2)) style stuff to do small multiples. Since introducing ggplot2 a semester or two later, we've been working on making the analysis as coherent as possible so students aren't having to move between different conceptual models of what data are, how they're stored and how we operate on them. The use of the %>% pipe is left as a bonus for those who feel comfortable programming, but the rest of the class will still be learning about gather, spread, group_by, summarise, summarise_each, and mutate. Oh, and I'm giving two two-hour lectures this semester, repeating for different groups within the cohort. It's weird.