---
title: Finishing off projects
author: Sam Clifford
date: 2017-05-31
---

One of the issues with working on a number of multidisciplinary projects at the same time is that stuff always ends up taking longer than expected and it interrupts progress on any given one. That said, the report for the Great Barrier Reef project I've been working on has been finalised and accepted, and the paper on modelling jaguar presences and abundances has been finished and is [published](http://onlinelibrary.wiley.com/doi/10.1002/env.2446/full). Since I've been working on these larger projects I've started putting together a [site](https://samclifford.github.io) that is an alternative to a CV, a sort of research portfolio that lists the projects I've worked on and the papers that have come out of them. I figured that I can't list all the papers and a description of them in my CV as it'll blow out to a huge number of pages and be more like a biography. It's all done in R Markdown knitted to a Tufte-inspired HTML template with a little CSS thrown in to modify the fonts and table of contents. It wasn't actually that difficult to do, and I learned a bit more about Markdown in the process. The next thing I'd like to be able to do is write a CSL file for styling the bibliography in such a way that some part of the reference itself is the URL, rather than it being tacked on the end, and abbreviate authors' first names. That way the end half of the page isn't so cluttered. I've been working with the Teaching and Learning team at QUT's Science and Engineering Faculty, and discussing with the physics and chemistry academics, on improving the maths in the Bachelor of Science degree. Nothing's finalised yet in terms of long term planning but we've been gradually solving problems over the last few years regarding students' background maths skills coming into the unit and recommending strategies that will help them get through their degrees. Feedback from the PULSE survey mid-semester indicates that we're still doing a good job but probably need to rebalance a few topics and give a gentler introduction to R. Since Nick Tierney came on board in SEB113 and redid the lab worksheets in R Markdown and created videos to show how to work through the exercises, I've been gradually introducing more and more R Markdown into the teaching workflow. The pie in the sky idea at the moment is to distribute lecture, lab and workshop material to students as a bookdown document that they can either clone or fork from a GitHub repository and work on. Any changes made to the book can be fetched so that students always have the most up to date version of the notes. The course could even be forked from one semester to another, or the book treated as releases. A number of the tutors in SEB113 are sold on R Markdown and the ability to include R analysis and LaTeX formatting in a set of slides, report or webpage, so there'd definitely be the staff to do it. There are certainly more pressing issues to solve around content and programming in general before we try to push first year science students into using code sharing platforms to download a textbook.